### ISSUE TITLE
[control plane][FE] deployment list should be queried as well every time when user switch to "deployment history" tab of a mapping use case

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#101]
**Issue description**

Now every time when user switch to "deployment history" tab of a mapping use case, only latest running deployment are queried, deployment list should be queried as well.

This is actually a regression.

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/0853bc4c-443e-4a4b-9940-a28eadda17b3)
