### ISSUE TITLE
[control plane][FE] "OK" button in select panel of mapping page should be always visible

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#102]
**Issue description:**

Now in select panel of mapping page, when API list to be selected is very long, user has scroll down to the end of list to view "OK" button and click it.

![Image](https://github.com/user-attachments/assets/e91eb0c1-ddcf-483d-bea8-322d5ad7a6c3)

![Image](https://github.com/user-attachments/assets/cf4a5d79-bd49-4c90-a736-74e48aab1c50)

**Expected:**
"OK" button in select panel of mapping page should be always visible

**Comment by emmawu001** [comment]
<img width="748" alt="image" src="https://github.com/user-attachments/assets/b5362af5-ad91-4aef-b6a9-1f175a3785dc">
Sometimes the panel header is invisible too. The panel header and footer (with OK button" should be frozen and always be visible like a standard drawer.

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/bc7d350f-097e-445d-8c3e-0faea67b1d24)
