### ISSUE TITLE
[control plane][FE] Input box can be expanded in input state to fit the text length in it in request and response mapping page

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#103]
**Issus description**

In request or response mapping page, when user click into the select box to input or update selected property, when the property name is longer than box length, user has to move to the end of the name to update it 

![Image](https://github.com/user-attachments/assets/a03518c6-ddbe-4206-8852-1efda949e11b)

**Expected**
box can be expanded in input state to fit the text length to allow user to view the full text of property name

the change should be applied to all select box that user could update.

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/507ef387-c359-4ea1-8f8e-5d7f26fa31e8)
