### ISSUE TITLE
[FEATURE] [Control Plane]  Mapping template upgrade result report

### ISSUE THREAD

**Issue by kuangxiang20240501** [mycloudnexus/kraken#105]
**Mapping template upgrade result report**

- control plane upgrade
  - begin time
  - end time 
  - mapping template version
- stage data plane upgrade
  -  begin time
  - end time
  - mapping template version
- production data plane upgrade
  - begin time
  - end time 
  - mapping template version

**Comment by cheng0504** [comment]
pass 
![Image](https://github.com/user-attachments/assets/810c6f04-b6f5-49a3-a52f-81956f7f5af9)

**Comment by cheng0504** [comment]
dev self test by zhiyuan
