### ISSUE TITLE
[BUG] Use new BE API to show 3 planes' mapping template version. 

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#106]
**Describe the bug**
<img width="855" alt="image" src="https://github.com/user-attachments/assets/880cf20b-dc2d-4b92-a392-7c96ceb0e877">

**Expected behavior**
Use new BE API to show 3 planes' mapping template version.

**Comment by miyaflowercat** [comment]
The following 3 properties in the response of  /system-info endpoint represent mapping template versions of 3 planes:

- controlProductVersion
- stageProductVersion
- productionProductVersion

**Comment by cheng0504** [comment]
@james-tran-3005 currently there are 2 stage
![Image](https://github.com/user-attachments/assets/182faaa4-d5f6-449c-b4da-f2b2e792ba1b)
