### ISSUE TITLE
[BUG] Incorrect node status 

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#107]
**Describe the bug**
<img width="1402" alt="image" src="https://github.com/user-attachments/assets/7d545aa7-d7f9-4942-8dde-1ff5d2263b1d">

<img width="1553" alt="image" src="https://github.com/user-attachments/assets/1a081add-e81d-4c6d-b8be-9ee93a1f90c3">

**Expected behavior**
In this case, the 2nd step(stage data plane) does no start to upgrade, so it should not show "Upgrading" status in it is node in the 1st screenshot.

**Comment by miyaflowercat** [comment]
![Image](https://github.com/user-attachments/assets/a007466d-ab16-47bf-9b86-d67b92ae1dad)

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/b4fe237a-8924-4caf-bc09-d327e1746055)
