### ISSUE TITLE
[BUG] When upgrading, the icon should be rotating rather than being static. 

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#108]
**Describe the bug**
<img width="855" alt="image" src="https://github.com/user-attachments/assets/306ab257-cfdf-44e7-8647-81870d9eec63">

**Expected behavior**
When upgrading, the icon in "Upgrading" button should be rotating rather than being static.

**Comment by cheng0504** [comment]
for this bug, miya asks this button to be rotated, but currently it is still static(unclickable), is this as expected?
![Image](https://github.com/user-attachments/assets/b2a96ecf-2ffd-4617-8d2c-b1fdc7365fed)

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/ce83a646-c1b6-45fc-8cad-2aa0611c84f2)
