### ISSUE TITLE
[BUG] Plane name is missing

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#109]
**Describe the bug**
Plane name is missing, thus user will not show which version is for which plane.
<img width="255" alt="image" src="https://github.com/user-attachments/assets/2ee77352-12a1-4de4-bf55-810c10e0bdb7">

**Expected behavior**
<img width="452" alt="image" src="https://github.com/user-attachments/assets/ef2d51e0-69d5-4e08-875c-490d31d983c0">

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/2c625e22-655c-4e8b-ba41-f828cffdf26c)
