### ISSUE TITLE
[BUG] Did not refresh the release page info when user click "Done" to complete a mapping template upgrade. 

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#110]
**Describe the bug**
Did not refresh the release page info when user click "Done" to complete a mapping template upgrade. 

**Expected behavior**
After user did a complete template version upgrade and click "Done" to go back to the release list page, should refresh the page automatically and ensure the "release version status" "Current version" and node status in the upgrade status panel is the latest.
<img width="1582" alt="image" src="https://github.com/user-attachments/assets/285df07f-32ca-4f84-a0a9-4e1ef63111f1">

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/4acad7c9-2fbc-430c-9c7d-9d94189f13cd)
