### ISSUE TITLE
[BUG] Should show "-" until the upgrade is done for each plane. 

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#113]
**Describe the bug**
<img width="1301" alt="image" src="https://github.com/user-attachments/assets/1a9f05a5-7254-4a8c-a72d-b0168fdcc515">
In the release list page, for the upgrading node(Stage data plane), it show the "To" time.

**Expected behavior**
Should show "-" in "To" field until the upgrade is done for each plane. ("From": start time, "To": finish time)

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/149be2dd-1906-4909-9169-a84ec9130a69)
