### ISSUE TITLE
[FEATURE] allow control plane user to push api activity log to external system

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#122]
as a control plane admin user, I can push selected API activity log to other system through a registered callback for debugging purpose

a/c:

- admin can push api activity logs by selecting a time range and env(stage or production) only if callback is registered
- max time range is 7 days
- Push history is available
   -- who
   -- when
   -- env
   -- time range
   -- status - in progress, done, failed

this feature should be able to be hided through a feature flag

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/b18e111f-5ed6-49c2-a592-3edb6e61776b)
could select starttime, endtime, and env
