### ISSUE TITLE
[improvement] "User role" and "Enable state" filters do not work

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#129]
**Describe the bug**
"User role" and "Enable state" filters do not work
<img width="1688" alt="image" src="https://github.com/user-attachments/assets/1a4f1865-da9a-4e36-9358-20bf9977de47">

**Expected behavior**
Filter can work normally.

**Comment by xuelianhan007** [comment]
ENDPOINT: `GET /products/{productId}/buyers?status=activated&role=USER`
status: activated or deactivated
role: USER or ADMIN

**Comment by cheng0504** [comment]
works now
![Image](https://github.com/user-attachments/assets/0c3cb378-0093-45f5-9323-071cd9321901)
pass.
