### ISSUE TITLE
[mapping template][improvement] template updates for 4 get order by id use cases

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#134]
**Impacted use cases**
1. get UNI add order by id
2. get Eline add order by id
3. get UNI delete order by id
4. get Eline delete order by id

**Updates required**
- response mapping
   - - change completeDate as optional mapping
   - - add productOrderItem[0].completionDate as optional mapping
   - - add productOrderItem[0].expectedCompletionDate as optional mapping

please indicate which mapping template version it will be in

**Comment by cheng0504** [comment]
eline  state = completed
{{host}}/mefApi/sonata/productOrderingManagement/v10/productOrder/e642a765-1d56-4b5e-9209-1194aa84559a?buyerId=qe1company
![Image](https://github.com/user-attachments/assets/4e4ddd7c-c69f-49fd-b840-82bc93415e00)

port state != completed
{{host}}/mefApi/sonata/productOrderingManagement/v10/productOrder/e32b7842-b4b2-45e3-b49a-dadfb5d8b3ff?buyerId=qe1company
![Image](https://github.com/user-attachments/assets/0d3ad1fb-ff7d-4881-916b-5063bcd35a4a)
