### ISSUE TITLE
[improvement] restore button on mapping page does not restore seller endpoint

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#143]
**Reproduction steps**

1. get into a mapping page with seller endpoint configured
2. delete seller api endpoint mapped in UI by clicking "x"
3. it will clear the request mapping and response mapping
4. click "restore" button
5. it only restores request mapping and response mapping in FE
6. seller api endpoint is not restored

![Image](https://github.com/user-attachments/assets/7482cf2a-a757-44ef-9bca-0c2a84d66cf8)

**Comment by cheng0504** [comment]
not fixed
![Image](https://github.com/user-attachments/assets/2f36ad73-b1e9-4bb9-8f72-3f585c008671)

**Comment by cheng0504** [comment]
remove the selected api and click restore, the api is not recovered.

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/c88c6c74-c717-4d90-879b-747b01a599d3)
