### ISSUE TITLE
[Improvement] Show Internal user name in deploy history list of mapping page and deployment history of deployments

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#157]
**Issue description**

In deploy history list of mapping page and deployment history of deployments, some "deployed by" are missing because the user is a internal user like "SYSTEM UPGRADE", FE failed to show it because of a filter of user list - /api/users?size=200&page=0&filterInternalUser=true

**expected**
When query user list for those two pages, remove the filterInternalUser=true from the user list api call, so that FE could be be able to show the user name.

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/e3303e80-c15f-4d84-a574-91273574e4e1)

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/5ed4ad21-eb78-4639-b042-34d2b2347a5c)
