### ISSUE TITLE
[improvement] reject duplicate push request if the first one is not completed yet

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#161]
**Given**

a push request is either aknowledged or in progress

**when**

a new push request is triggered by user for total same env and same time range

**Then**

Kraken should reject the request with clear reason

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/9425b6f6-1f72-45c5-8d6f-e89b6024430b)
pass
