### ISSUE TITLE
[1.0][rc]API path display improvement

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#162]
<img width="713" alt="image" src="https://github.com/user-attachments/assets/b26601ed-e82d-40b0-9755-92c0a952a227">

**Comment by cheng0504** [comment]
rule 1:
![Image](https://github.com/user-attachments/assets/8f22b1fb-000f-4abe-8b23-bd7345f2ae5d)

![Image](https://github.com/user-attachments/assets/e00a025f-5a39-4c73-aa11-eb600478ec22)

**Comment by cheng0504** [comment]
rule 2:
![Image](https://github.com/user-attachments/assets/1b28684d-3f44-43ac-a319-ddbdcee79169)
![Image](https://github.com/user-attachments/assets/d6850a2b-d946-40a1-8235-44d177f324a0)

**Comment by cheng0504** [comment]
rule 3:
![Image](https://github.com/user-attachments/assets/c536a9c8-c89e-49f2-b550-3b45f21bf400)
