### ISSUE TITLE
[BUG]   control plane deployment detail is empty

### ISSUE THREAD

**Issue by kuangxiang20240501** [mycloudnexus/kraken#163]
**Describe the bug**
 when click the link of control plane in upgrade page , nothing show in th ui 
![2024-11-15_16-52](https://github.com/user-attachments/assets/66765872-3cae-4047-b682-910e8cf1db7b)

![2024-11-15_16-50](https://github.com/user-attachments/assets/b0f1af12-3b6c-4275-9b8c-580ac524e4da)

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/6cf07f3a-3e8d-4c2d-bc50-8e2551b0b326)
