### ISSUE TITLE
[1.0][rc] create UNI order - remove the constant validation of place.@type

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#165]
**Current Behavior**

Kraken will validate if the value of **productOrderItem[].product.place[].@type** in "Create UNI order" is "GeographicAddressRef" before

**Expected Behavior**

remove the constant value validation

**Comment by xuelianhan007** [comment]
Removed the constant value validation of 'place.@type' but remained the existence of this node.

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/1e708f20-f30c-4901-bc61-6e514dbea5d4)
