### ISSUE TITLE
[BUG] sometimes when switching from one environment to the other, no any data shows up.

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#168]
**Describe the bug**
Actually there is data to show, but sometimes when switching from one environment to the other, no any data shows up.
<img width="1546" alt="image" src="https://github.com/user-attachments/assets/83031b5d-a813-48cf-847c-6f3930c908f1">

**Expected behavior**
Show up activity data properly.

**Comment by cheng0504** [comment]
doesn't monitor this issue in latest build
pass![Image](https://github.com/user-attachments/assets/5e7adb1a-a241-452e-a43a-6418c8643ea9)
