### ISSUE TITLE
[BUG] When hovers on the tag, notice the server name will move up a little bit

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#172]
**Describe the bug**
When hovers on the tag, notice the server name will move up a little bit
https://github.com/user-attachments/assets/849bf7ff-60df-45bd-a926-c82ec93956ee

**Expected behavior**
When moues over on the "In use" tag, only the tag changes to "Check details" link button, the server itself should no change/move.

**Comment by cheng0504** [comment]
still existed
