### ISSUE TITLE
[BUG] Font size and font weight not correct

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#177]
**Describe the bug**
<img width="551" alt="image" src="https://github.com/user-attachments/assets/7ebda8d2-63e8-4204-8256-9cca0d6a0eee">
Font size and font weight not correct

**Expected behavior**
Should be 16px, font weight: 500 (medium).

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/1d8c94fc-51b3-4a0e-943a-578ec8ac0f28)
