### ISSUE TITLE
[FEATURE] [control plane] api activity statistics diagram

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#19]
a/c:

- User would be able to view the following statistics regarding api activity within selected time range for a specific data plane env(stage or production)
- request trend, break down by status(success or error)
- daily error breakdown by response status code
- top 7 popular endpoints and calling numbers
- all the data could be either for all buyers or filtered by specific buyer company

**Comment by miyaflowercat** [comment]
Get API requests stats


url -  /products/{productId}/envs/{env}/statistics/api-activity-requests?timezone={timezone}&requestStartTime={date}&requestEndTime={date}
request 
curl --location --request GET 'http://localhost:8001/products/mef.sonata/envs/2fd92244-a8d1-43fc-b76d-d87ffb0172f4/statistics/api-activity-requests?timezone=Europe%2FWarsaw&requestStartTime=1729116000000&requestEndTime=1729375200000' \
--header 'Authorization: Bearer XXX' 
 

response 
{
  "code": 200,
  "message": "OK",
  "data": {
    "requestStatistics": [
      {
        "date": "2024-10-19T00:00:00+02:00",
        "success": 393,
        "error": 615
      },
      {
        "date": "2024-10-18T00:00:00+02:00",
        "success": 357,
        "error": 651
      },
      {
        "date": "2024-10-17T00:00:00+02:00",
        "success": 388,
        "error": 620
      }
    ]
  }
}

**Comment by miyaflowercat** [comment]
Get error statistics

url -  /products/{productId}/envs/{env}/statistics/error-requests?timezone={timezone}&requestStartTime={date}&requestEndTime={date}
request 
curl --location --request GET 'http://localhost:8001/products/mef.sonata/envs/2fd92244-a8d1-43fc-b76d-d87ffb0172f4/statistics/error-requests?timezone=Europe%2FWarsaw&requestStartTime=1729116000000&requestEndTime=1729375200000' \
--header 'Authorization: Bearer XXX' 
 

response 
{
  "code": 200,
  "message": "OK",
  "data": {
    "errorBreakdowns": [
      {
        "date": "2024-10-19T00:00:00+02:00",
        "errors": {
          "400": 245,
          "401": 239,
          "404": 24,
          "500": 107
        }
      },
      {
        "date": "2024-10-18T00:00:00+02:00",
        "errors": {
          "400": 228,
          "401": 229,
          "404": 24,
          "500": 170
        }
      },
      {
        "date": "2024-10-17T00:00:00+02:00",
        "errors": {
          "400": 237,
          "401": 229,
          "404": 24,
          "500": 130
        }
      }
    ]
  }
}

**Comment by miyaflowercat** [comment]
Get most popular endpoints

url -  /products/{productId}/envs/{env}/statistics/most-popular-endpoint?requestStartTime={date}&requestEndTime={date}
request 
curl --location --request GET 'http://localhost:8001/products/mef.sonata/envs/2fd92244-a8d1-43fc-b76d-d87ffb0172f4/statistics/most-popular-endpoint?requestStartTime=1729116000000&requestEndTime=1729202400000' \
--header 'Authorization: Bearer XXX' 
 

response 
{
  "code": 200,
  "message": "OK",
  "data": {
    "endpointUsages": [
      {
        "method": "GET",
        "endpoint": "/mefApi/sonata/order/789",
        "usage": 117,
        "popularity": 11.6
      },
      {
        "method": "GET",
        "endpoint": "/mefApi/sonata/product/825",
        "usage": 78,
        "popularity": 7.73
      },
      {
        "method": "GET",
        "endpoint": "/mefApi/sonata/product/789",
        "usage": 78,
        "popularity": 7.73
      },
      {
        "method": "POST",
        "endpoint": "/mefApi/sonata/order/789",
        "usage": 72,
        "popularity": 7.14
      },
      {
        "method": "GET",
        "endpoint": "/mefApi/sonata/geographicAddressManagement/v7/geographicAddress/825",
        "usage": 65,
        "popularity": 6.44
      },
      {
        "method": "GET",
        "endpoint": "/mefApi/sonata/order/825",
        "usage": 52,
        "popularity": 5.15
      },
      {
        "method": "POST",
        "endpoint": "/mefApi/sonata/product/789",
        "usage": 48,
        "popularity": 4.76
      }
    ]
  }
}

**Comment by miyaflowercat** [comment]
all BE API calls from FE failed with 400 bad request.![Image](https://github.com/user-attachments/assets/e5030ae2-bf2d-491b-8cc4-281ec1d00d55)

**Comment by jaroslawmalekcodete** [comment]
Hi @KsiBart 
the FE should use requestStartTime instead of startTime and requestEndTime instead of endTime. 

example
```
curl --location --request GET 'https://kraken-portal-cn.dev.consolecore.cc/api/products/mef.sonata/envs/b2d775e5-44ad-43cb-8dd4-6fbe52585ec9/statistics/api-activity-requests?requestStartTime=2024-10-12T08%3A28%3A08%2B01%3A00&requestEndTime=2024-11-12T08%3A28%3A08%2B01%3A00' \
--header 'Authorization: Bearer  XXX'
```
response
```json
{
    "code": 200,
    "message": "OK",
    "data": {
        "requestStatistics": [
            {
                "date": "2024-11-01",
                "error": 12
            },
            {
                "date": "2024-11-04",
                "error": 3
            },
            {
                "date": "2024-11-05",
                "error": 1
            },
            {
                "date": "2024-11-06",
                "success": 2
            },
            {
                "date": "2024-11-07",
                "success": 1,
                "error": 38
            },
            {
                "date": "2024-11-08",
                "success": 54,
                "error": 30
            },
            {
                "date": "2024-11-09",
                "success": 62,
                "error": 6
            },
            {
                "date": "2024-11-10",
                "success": 2,
                "error": 4
            },
            {
                "date": "2024-11-11",
                "success": 11,
                "error": 21
            },
            {
                "date": "2024-11-12",
                "success": 11,
                "error": 6
            }
        ]
    }
}
```

**Comment by miyaflowercat** [comment]
![Image](https://github.com/user-attachments/assets/b3afede9-a326-4a45-991c-d9623e2722f0)
The line should be continuous

**Comment by miyaflowercat** [comment]
BE need to handle the data without status code - put them into error group

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/be5f2116-4890-419a-83ee-59be8ef9bfc6)
