### ISSUE TITLE
[BUG] Text color not correct

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#193]
**Describe the bug**
<img width="699" alt="image" src="https://github.com/user-attachments/assets/019035de-ebff-4c74-95f0-64e30e072b3e">

**Expected behavior**
Show text primary color following figma design.
<img width="939" alt="image" src="https://github.com/user-attachments/assets/1b539801-35ac-43e3-b9f3-c486f5c83d13">

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/b19c5e33-2728-4b76-a761-e9e3fbc83b2d)
