### ISSUE TITLE
[BUG] Empty states of API activity charts

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#196]
**Describe the bug**
<img width="1541" alt="image" src="https://github.com/user-attachments/assets/22332dd9-02de-4a17-bbc6-77977802eadd">

**Expected behavior**
Please follow figma design to update this part.
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/4b574898-5011-4477-90f4-f1c7488cdbb6">

**Comment by cheng0504** [comment]
mock response
pass
![Image](https://github.com/user-attachments/assets/05d02baa-bb15-4a13-bb0b-7d26ca7bba41)
