### ISSUE TITLE
[BUG] Release history page issue

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#203]
**Describe the bug**
Show "No matched release" when loading page.
<img width="1799" alt="image" src="https://github.com/user-attachments/assets/49b5ae04-137c-496d-8f0e-1a82de41c1ed">

After loading, no any release is selected by default. 
<img width="1799" alt="image" src="https://github.com/user-attachments/assets/44f9fc11-94a8-4183-9cd1-8d0761371a6c">

**Expected behavior**
1. When loading page, should not show "Not matched release"-empty states.
2. After 1st loading, the 1st release in the "All' list should be selected by default.

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/4b5cbb1d-f42e-43ee-9f5e-eabe5be48f1f)

![Image](https://github.com/user-attachments/assets/78784b27-13ee-4ef6-86e2-929680dc4c4e)
