### ISSUE TITLE
[1.0][rc]quote and quote item state should be "unableToProvide" when target API return a negative price

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#207]
a/c:

- for "create UNI add sync quote" and "create Eline add sync quote"
   - when target API return a negative price or a empty price
     - quoteItem[0].state == unableToProvide

@cheng0504

**Comment by cheng0504** [comment]
send bandwidth = 1000000
![Image](https://github.com/user-attachments/assets/93ecb550-794b-4de1-8d80-1a7a02d06b65)

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/a1fe07d1-627f-44a4-aae0-0823d054564d)
