### ISSUE TITLE
[Enhancement] Allow user to set value enumeration for a sonata property in Request mapping and add Validation

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#209]
As a control plane user,  when I create request mapping between sonata API and target API, I could be able to 
add value enumeration for specific sonata properties

e.g. bandwidth range [1000, 10000]

later when this sonata use case is triggered, kraken will do request property value validation for those properties that user set value enumerations

- if pass validation, kraken will continue the processing
- if failed, kraken will fail the request with 422

**Comment by cheng0504** [comment]
wait for UI ready

**Comment by cheng0504** [comment]
pass
<img width="600" alt="Image" src="https://github.com/user-attachments/assets/a1baacc8-52fa-4521-ba83-b6c888c8f976" />
<img width="1344" alt="Image" src="https://github.com/user-attachments/assets/33d0eacf-9338-4732-bfd5-7d03b8339136" />
