### ISSUE TITLE
[BUG] [1.0][rc] quote UNI add - remove the constant validation of place.@type

### ISSUE THREAD

**Issue by cheng0504** [mycloudnexus/kraken#215]
Current Behavior

Kraken will validate if the value of quoteItem[0].product.place[].@type in "Create UNI Quote" is "GeographicAddressRef" before

Expected Behavior

remove the constant value validation

**Comment by xuelianhan007** [comment]
Removed the constant value validation but remained the node non-null checking.

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/7d068911-9b03-4f25-868f-0b71fdf40810)

![Image](https://github.com/user-attachments/assets/adc18c28-24f8-4c63-8ea6-bb2842d0f0b7)
