### ISSUE TITLE
[1.0][rc][mapping template] 4 get order by id - set 2 subsidiary properties of "state" property when its value is "completed"

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#221]
a/c:

- for 4 get order by id, in response mapping, regarding "state" property
      - when value is "completed", then return the following properties, otherwise not
         - completionDate
         - productOrderItem[0].completionDate

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/1e77c9c1-2310-4e06-8acb-0f45c438e129)

**Comment by cheng0504** [comment]
pass 
![Image](https://github.com/user-attachments/assets/19cd1713-39f8-4d9a-9a80-d60bdf4b4e0d)

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/b12687d1-21ef-4092-ba39-c124bfd48e52)
