### ISSUE TITLE
[1.0][rc] no pagination support in buyer management

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#223]
**Issue description**

In buyer management, under 2 tabs of "stage environment" and "Production Environment", pagination support is missing which leads to FE only shows one page data

**expected**
- support pagination, 20 records a page

**Comment by cheng0504** [comment]
pass

![Image](https://github.com/user-attachments/assets/458f6ecf-d09b-4666-b52c-970ecf0908ff)
