### ISSUE TITLE
[improvement] [FE]side drawer can be closed by clicking anywhere outside the drawer

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#227]
a/c:

- all side drawers in control plane portal can be closed as well by clicking anywhere outside the drawer, right now it can only be closed by clicking "x" button

**Comment by cheng0504** [comment]
pass
works now- all side drawers in control plane portal can be closed as well by clicking anywhere outside the drawer

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/43eff0e5-debc-468a-90ae-9c8128ea769d)
![Image](https://github.com/user-attachments/assets/020d1187-bcae-4aad-ae1b-1a3b32108b3c)
