### ISSUE TITLE
[Improvement] add productOrderItem[0].product.id in response mapping of create UNI add order and create Eline add order

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#23]
**Describe the Issue**
There is a customized property "instanceId" in response mapping of create UNI add order and create Eline add order to mapping seller product instance id

**Expected behavior**
add productOrderItem[0].product.id in response mapping of create UNI add order and create Eline add order
- optional mapping to make sure it can be compatible with old data

**Screenshots**
n/a

**Additional context**
- need to think about how to migrate legacy data

**Comment by zhiyaoPCCW** [comment]
Add another additional field 'productOrderItem[0].product.id'. no need to migrate data.

**Comment by cheng0504** [comment]
@xuelianhan007 
after setting: 

@{{productOrderItem[0].product.id}} == @{{id}}, get the following error:

![Image](https://github.com/user-attachments/assets/0009dabe-3a7c-4248-9d10-996634cbb46f)

**Comment by cheng0504** [comment]
and we need to remove  instance id from the target mappers file of both UNI and Eline:
![Image](https://github.com/user-attachments/assets/848a3833-2dc2-4dca-acec-df9c2e816dc8)

**Comment by xuelianhan007** [comment]
![image](https://github.com/user-attachments/assets/024e381f-b1a8-4272-b999-f9380ce273e2)

**Comment by xuelianhan007** [comment]
![image](https://github.com/user-attachments/assets/7e655129-d1f7-4349-a3f9-a84619592a8d)
![image](https://github.com/user-attachments/assets/96c3d5fc-8e4c-4fc3-8869-a6eaf0796135)

**Comment by cheng0504** [comment]
@miyaflowercat 
should we set @{{productOrderItem[0].product.id}} == @{{id}}? as there is no "port.id" in cc's response:
![Image](https://github.com/user-attachments/assets/10b1686b-bcaa-433a-9567-46a4d8281c6e)

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/8ff77039-34d7-4ade-97b6-e0a1a9dfe55b)

**Comment by cheng0504** [comment]
after setting, @{{productOrderItem[0].product.id}} == @{{id}}
![Image](https://github.com/user-attachments/assets/1a944898-90b1-49fd-a096-379715c8a612)

**Comment by cheng0504** [comment]
pass.
for eline:
            {
                        "role": "INSTALL_LOCATION",
                        "id": "6356792a4806220015488631",
                        "@type": "GeographicAddressRef"
                    }
                ],
                "id": "6732ff24eaea480b127910df"
            },


for uni:
                "place": [
                    {
                        "role": "INSTALL_LOCATION",
                        "id": "6356792a4806220015488631",
                        "keyName": "qe-dcf-1",
                        "@type": "GeographicAddressRef"
                    }
                ],
                "id": "6732ff83eaea480b127910fa"
