### ISSUE TITLE
[mapping template] allow setting bandwidth value options for create UNI add order

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#237]
As a service delivery engineer, I would be able to 

set value options for @{{productOrderItem[0].product.productConfiguration.bandwidth}} in request mapping of create UNI add order

and

specify value type - numeric or non-numeric

- numeric
  - continuous values
     - input min and max
     - example :  [1-100]
  - discrete values
     - input all available values 
     - example : [10, 100]
- non-numeric
  - input all available values
  - examples : [month, year, day]

and after the mapping configuration is deployed into data plane, kraken will do value validation for sonata properties with value configured and report 422 if validation failed

**Comment by cheng0504** [comment]
write down some details about how you did the test, list some test steps. take some snapshot

**Comment by cheng0504** [comment]
range：
<img width="843" alt="Image" src="https://github.com/user-attachments/assets/99480194-e5e9-4a5f-be52-6eb79db92f49" />
enum：
<img width="822" alt="Image" src="https://github.com/user-attachments/assets/255a76e7-7e9b-43f9-bc06-0baca3813bb6" />
