### ISSUE TITLE
[BUG] [FE] running api mapping list and deployment history under "deployment" module are not taking up whole screen

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#238]
**Describe the bug**
running api mapping list and deployment history under "deployment" module are not taking up whole screen

**Screenshots**
![Image](https://github.com/user-attachments/assets/68bfa1fb-222f-4741-8b03-69c9be8334a9)

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/a5b07fee-83cf-41e1-bf10-f5b4e40063ff)
