### ISSUE TITLE
[FEATURE] Make API mapping page left panel draggable

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#246]
<img width="1835" alt="image" src="https://github.com/user-attachments/assets/f0e3a1f8-fff7-4c80-bd05-9c7967ea273d">

**Comment by miyaflowercat** [comment]
left panel should be in correct scrollable state when the panel is not showing the full endpoint
![Image](https://github.com/user-attachments/assets/8b0359f0-ba71-4d8d-ac2d-bfbdedae811e)

**Comment by miyaflowercat** [comment]
based on feedback from Emma, the left panel should be responsive within minimum width

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/07f733c1-9954-4a74-84a4-8ed742776003)
