### ISSUE TITLE
[BUG] user start guide is reporting that at least one seller API server is created but actually not

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#247]
**Describe the bug**
user start guide is reporting that at least one seller API server is created but actually not

/start/guide/mef.sonata?kind=kraken.component.api

{
    "code": 200,
    "message": "OK",
    "data": {
        "sellerApiServerRegistrationInfo": {
            "atLeastOneSellerApiRegistered": true
        },
        "apiMappingInfo": {
            "atLeastOneMappingCompleted": false
        },
        "deploymentInfo": {
            "atLeastOneApiDeployedToStage": false,
            "atLeastOneBuyerRegistered": false,
            "atLeastOneApiDeployedToProduction": false
        }
    }
}

checking seller api server list:
/v2/products/mef.sonata/components/mef.sonata/api-servers?kind=kraken.component.api&size=500&facetIncluded=true

{"code":200,"message":"OK","data":{"data":[],"total":0,"page":0,"size":500}}

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/365c2b31-62b8-47c8-b777-033b14607976)
