### ISSUE TITLE
[BUG] [FE] running mapping template version of 3 planes are not showing up

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#248]
**Describe the bug**
 running mapping template version of 3 planes are not showing up when no mapping template release is available
![Image](https://github.com/user-attachments/assets/887e09c3-beaf-46b3-9f84-097b4b27bb30)
![Image](https://github.com/user-attachments/assets/6f910312-2f01-4d12-af0a-e488dc775f63)

{
    "code": 200,
    "message": "OK",
    "data": {
        "id": "a4eee1b9-ca5e-4264-aba9-cbec3b331a23",
        "createdAt": "2024-11-29T06:50:56.95255Z",
        "updatedAt": "2024-11-29T07:09:20.667954Z",
        "controlProductVersion": "V1.6.0",
        "stageProductVersion": "V1.6.0",
        "productionProductVersion": "V1.6.0",
        "controlAppVersion": "1.0.0",
        "productKey": "mef.sonata",
        "productSpec": "grace",
        "key": "CONTROL_PLANE",
        "status": "RUNNING",
        "stageAppVersion": "1.0.0",
        "productName": ""
    }
}

**Comment by cheng0504** [comment]
monitor system-info response:
![Image](https://github.com/user-attachments/assets/16b37865-0cdd-499b-98d4-6c517138f081)
Template version could show up
![Image](https://github.com/user-attachments/assets/5e1efbf4-f2fd-46aa-83f6-1fdcc6bc5bbe)
