### ISSUE TITLE
[BUG] [BE] uni/eline quote add - "instantSyncQuote": false

### ISSUE THREAD

**Issue by cheng0504** [mycloudnexus/kraken#25]
if set "instantSyncQuote": false (api only support instantSyncQuote = true).

error message should be optimized.
![image](https://github.com/user-attachments/assets/9b402530-b56c-4e0a-8db9-691780223554)

expected result:

reason can be more explicit like 
api use case is not supported : disabled : instantSyncQuote==false

**Comment by cheng0504** [comment]
payload:
///
curl --location 'https://api.consoleconnect.com/Sonata/staging/mefApi/sonata/quoteManagement/v8/quote' \
--header 'Content-Type: application/json' \
--header 'Cookie: plb=7f8597cbdd145f9e' \
--data-raw '{
    "note": [],
    "requestedQuoteCompletionDate": "2027-12-31T23:00:00Z",
    "relatedContactInformation": [
        {
            "number": "111 222 333",
            "emailAddress": "buyerContact@mef.com",
            "role": "buyerContactInformation",
            "postalAddress": null,
            "organization": "MEF",
            "name": "Joe Buyer",
            "numberExtension": null
        }
    ],
    "externalId": "ORDERABLE_ALTERNATE [8203] Sync Quote FIRM - ADD",
    "buyerRequestedQuoteLevel": "firm",
    "projectId": "MEF OIT",
    "instantSyncQuote": true,
    "quoteItem": [
        {
            "requestedQuoteItemTerm": {
                "name": "UNI Item Term",
                "duration": {
                    "amount": 1,
                    "units": "calendarMonths"
                },
                "endOfTermAction": "roll",
                "description": "no description",
                "rollInterval": {
                    "amount": 1,
                    "units": "calendarMonths"
                }
            },
            "note": [],
            "product": {
                "id": null,
                "href": null,
                "place": [
                    {
                        "role": "INSTALL_LOCATION",
                        "href": null,
                        "id": "6356792a4806220015488631",
                        "@type": "GeographicAddressRef",
                        "@schemaLocation": null
                    }
                ],
                "productConfiguration": {
                    "@type": "UNI",
                    "bandwidth": 1000,
                    "bandwidthUnit": "MBPS",
                     "name" : "test-qc01",
                    "paymentType" : "invoice"
                },
                "productOffering": {
                    "id": "UNI",
                    "href": null
                },
                "productRelationship": []
            },
            "productOfferingQualificationItem": {
                "productOfferingQualificationId": "",
                "alternateProductProposalId": null,
                "productOfferingQualificationHref": null,
                "id": "UNI"
            },
            "relatedContactInformation": [
                {
                    "number": "111 222 333",
                    "emailAddress": "quoteItemTechnicalContact@mef.com",
                    "role": "quoteItemTechnicalContact",
                    "postalAddress": null,
                    "organization": "MEF",
                    "name": "David Item",
                    "numberExtension": null
                },
                {
                    "number": "111 222 333",
                    "emailAddress": "quoteItemLocationContact@mef.com",
                    "role": "quoteItemLocationContact",
                    "postalAddress": null,
                    "organization": "MEF",
                    "name": "Konrad Item Location",
                    "numberExtension": null
                }
            ],
            "agreementName": null,
            "action": "add",
            "dealReference": null,
            "id": "UNI",
            "requestedQuoteItemInstallationInterval": {
                "amount": 10,
                "units": "calendarMonths"
            },
            "quoteItemRelationship": []
        }
    ]
}'

**Comment by cheng0504** [comment]
@xuelianhan007 
uni quote - "instantSyncQuote": false, matrix check is not as expected.
![Image](https://github.com/user-attachments/assets/1e6953e1-76f9-4d43-b9c7-3c17d516a27b)

**Comment by xuelianhan007** [comment]
![image](https://github.com/user-attachments/assets/442dae78-729a-4e55-8898-61370511438a)

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/8943aec8-373f-46a6-a8a4-810e468a3a6a)
pass in uni and eline
