### ISSUE TITLE
[BUG] [BE] quote uni/eline add - "productConfiguration"- "@type": "UNI1"

### ISSUE THREAD

**Issue by cheng0504** [mycloudnexus/kraken#26]
"productConfiguration": {
"@type": "UNI1", — only support UNI but set with 'UNI1'
Error message should be updated, as 422 not supported.
![image](https://github.com/user-attachments/assets/e1c3b28f-4408-4779-b619-bd2994848ea0)

expected result:

reason should be
api use case not supported :not supported: quoteItem[0].product.productConguration.@type should be either UNI or ACCESS_E_LINE

**Comment by cheng0504** [comment]
payload:
curl --location 'https://api.consoleconnect.com/Sonata/staging/mefApi/sonata/quoteManagement/v8/quote' \
--header 'Content-Type: application/json' \
--header 'Cookie: plb=7f8597cbdd145f9e' \
--data-raw '{
    "note": [],
    "requestedQuoteCompletionDate": "2027-12-31T23:00:00Z",
    "relatedContactInformation": [
        {
            "number": "111 222 333",
            "emailAddress": "buyerContact@mef.com",
            "role": "buyerContactInformation",
            "postalAddress": null,
            "organization": "MEF",
            "name": "Joe Buyer",
            "numberExtension": null
        }
    ],
    "externalId": "ORDERABLE_ALTERNATE [8203] Sync Quote FIRM - ADD",
    "buyerRequestedQuoteLevel": "firm",
    "projectId": "MEF OIT",
    "instantSyncQuote": true,
    "quoteItem": [
        {
            "requestedQuoteItemTerm": {
                "name": "UNI Item Term",
                "duration": {
                    "amount": 1,
                    "units": "calendarMonths"
                },
                "endOfTermAction": "roll",
                "description": "no description",
                "rollInterval": {
                    "amount": 1,
                    "units": "calendarMonths"
                }
            },
            "note": [],
            "product": {
                "id": null,
                "href": null,
                "place": [
                    {
                        "role": "INSTALL_LOCATION",
                        "href": null,
                        "id": "6356792a4806220015488631",
                        "@type": "GeographicAddressRef",
                        "@schemaLocation": null
                    }
                ],
                "productConfiguration": {
                    "@type": "UNI",
                    "bandwidth": 1000,
                    "bandwidthUnit": "MBPS",
                     "name" : "test-qc01",
                    "paymentType" : "invoice"
                },
                "productOffering": {
                    "id": "UNI",
                    "href": null
                },
                "productRelationship": []
            },
            "productOfferingQualificationItem": {
                "productOfferingQualificationId": "",
                "alternateProductProposalId": null,
                "productOfferingQualificationHref": null,
                "id": "UNI"
            },
            "relatedContactInformation": [
                {
                    "number": "111 222 333",
                    "emailAddress": "quoteItemTechnicalContact@mef.com",
                    "role": "quoteItemTechnicalContact",
                    "postalAddress": null,
                    "organization": "MEF",
                    "name": "David Item",
                    "numberExtension": null
                },
                {
                    "number": "111 222 333",
                    "emailAddress": "quoteItemLocationContact@mef.com",
                    "role": "quoteItemLocationContact",
                    "postalAddress": null,
                    "organization": "MEF",
                    "name": "Konrad Item Location",
                    "numberExtension": null
                }
            ],
            "agreementName": null,
            "action": "add",
            "dealReference": null,
            "id": "UNI",
            "requestedQuoteItemInstallationInterval": {
                "amount": 10,
                "units": "calendarMonths"
            },
            "quoteItemRelationship": []
        }
    ]
}'

**Comment by cheng0504** [comment]
UNI/ELine Add also has this issue.

**Comment by cheng0504** [comment]
similar for action value. if we provide 'add1', kraken doesn't know which api to call.
<img width="627" alt="image" src="https://github.com/user-attachments/assets/e5f0423a-dedf-49b5-a005-41beb873c128">

**Comment by cheng0504** [comment]
<img width="844" alt="image" src="https://github.com/user-attachments/assets/ec12c982-2e0f-4492-ad96-ec5aeb974514">

**Comment by cheng0504** [comment]
@zhiyaoPCCW modify @type still get 500 error
![Image](https://github.com/user-attachments/assets/4f6e9d28-6f51-4226-a71f-2dc54fe5687b)

**Comment by xuelianhan007** [comment]
[
![image](https://github.com/user-attachments/assets/87efc64a-a460-4865-a214-e313d918b240)
](url)
[
![Screenshot from 2024-11-08 17-57-11](https://github.com/user-attachments/assets/9a2b98f1-a09d-4102-a06d-0f8d24aa0fb7)
](url)

**Comment by cheng0504** [comment]
for UNI: pass
![Image](https://github.com/user-attachments/assets/f88a1253-7716-4ebb-9f3c-6b7ddc83c11a)
![Image](https://github.com/user-attachments/assets/d83ccfb5-8a85-4909-a726-b24d6ff6491b)

**Comment by cheng0504** [comment]
for Eline:pass
![Image](https://github.com/user-attachments/assets/84f88e14-dc0d-49f3-8534-b8bef1cb2279)
![Image](https://github.com/user-attachments/assets/4c8a7163-d22b-4332-9be3-012f0b8231e6)
