### ISSUE TITLE
[BUG] [Data Plane] Make sure that undeployed use cases return correct response message

### ISSUE THREAD

**Issue by zhiyaoPCCW** [mycloudnexus/kraken#260]
For the below use cases, 

- retrieve address
- get order by id (4 cases)

If use case is not deployed yet, it will return error message like this: 
`{
    "code": "notFound",
    "reason": "Asset not found,key=mef.sonata.api-target.address.retrieve",
    "message": "time:Tue Dec 03 05:48:37 UTC 2024, error: Internal Server Error, path:/mefApi/sonata/geographicAddressManagement/v7/geographicAddress/616575899533990016228f22",
    "referenceError": "Asset not found,key=mef.sonata.api-target.address.retrieve"
}`

Expected: 

"reason": "api use case is not supported :not deployed",

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/70839c9b-95e1-466e-9458-2ca6801bca96)
