### ISSUE TITLE
Mapping page loading behavior enhancement

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#265]
**Describe the solution you'd like**
Keep the page frame/skeleton consistent during loading and after loading
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/a09b379b-46b6-42c7-ab85-7bfb0b879729">

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/dcf2e58e-4794-462b-b977-07f08e52d3f3)
pass
