### ISSUE TITLE
[BUG] For selected version, version number together with standard version name should change to highlighted color (primary blue)

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#267]
**Describe the bug**
<img width="422" alt="image" src="https://github.com/user-attachments/assets/5adb7253-84ce-452d-8b2e-1cafd8ae6334">

**Expected**
For selected version, version number together with standard version name should change to highlighted color (primary blue)
<img width="815" alt="image" src="https://github.com/user-attachments/assets/a22a3c8e-3835-4108-a080-d20352783ccf">

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/1c8845ff-7a39-403e-934b-cad23aeaf96f)
