### ISSUE TITLE
[FEATURE] Adjust current mapping template version to top right corner (Page header area)

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#268]
**Describe the solution you'd like**
Adjust current mapping template version to top right corner (Page header area)
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/66466ec1-84a8-4cbb-82db-d1c1a39bafab">

**Comment by miyaflowercat** [comment]
should be duplicate with issue#248

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/3a97c2b9-2d1b-4e0a-aeb5-316770f1675b)
pass
