### ISSUE TITLE
[Improvement] Mapping template upgrade>View details drawer

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#269]
**Describe the requirement**
1. Enlarge drawer width to accommodate all columns without horizontal scrolling inside the drawer
2. The message on the top should fit the drawer width. 
<img width="1795" alt="image" src="https://github.com/user-attachments/assets/28180560-8fcb-41cd-a35f-8f672958736b">

**Comment by cheng0504** [comment]
Still has the horizontal scrolling
![Image](https://github.com/user-attachments/assets/ddc5fca4-11ed-4e44-b4e9-77a832a50ec8)

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/f1d5c77a-97bc-478a-93c1-8df72a2c0a82)
