### ISSUE TITLE
[control plane][FE] filter user by role and enabled state

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#270]
a/c:

- In user management list, support filtering user by role and enable state
  - ENDPOINT: GET https://host-here/api/users?size=200&page=0&state=ENABLED&role=USER
     - state: ENABLED or DISABLED
     - role: USER or ADMIN

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/6465672a-4346-4c02-8a84-a4601db3f483)
pass
