### ISSUE TITLE
[FE][Improvement] remove unused button and add necessary tooltip

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#274]
a/c:
1. In "Deployment" ->" Deployment history" tab, remove "check details" button of each record and add tooltip to "verified for production"
![Image](https://github.com/user-attachments/assets/38f490a8-580c-49b4-a4c8-4c06b473f12f)
2. remove "compare" button in use case mapping page
![Image](https://github.com/user-attachments/assets/ecc4835d-4ae1-4444-9d18-8696e208c8a9)
3. remove "check details" button of each record and add tooltip to "verified for production" in use case deployment history page
![Image](https://github.com/user-attachments/assets/bcd28043-c2ba-4a5f-8d4e-dfd0927a06ef)

**Comment by miyaflowercat** [comment]
item 2 is not covered

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/abd0a855-a93e-45d5-917c-7631709647aa)
![Image](https://github.com/user-attachments/assets/864f4e84-8637-4aa1-8443-d2712234b49d)
![Image](https://github.com/user-attachments/assets/2bb3f84d-1528-4488-bb08-f6d551b7c174)
