### ISSUE TITLE
[mapping template] [request property type check]create address validation and get address by id

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#276]
a/c:
- request property type check are supported for create address validation and get address by id

**Comment by cheng0504** [comment]
<img width="826" alt="Image" src="https://github.com/user-attachments/assets/e143ff27-6fe8-4813-9895-fe3d1dcfd30f" />
regression on address

**Comment by cheng0504** [comment]
streetName not set in mapping file
not provide the priority, still check on kraken side,
should remove this check:
<img width="814" alt="Image" src="https://github.com/user-attachments/assets/03ba04d4-e8a4-4b4b-bde7-22fa39b5a08f" />

**Comment by cheng0504** [comment]
pass
<img width="648" alt="Image" src="https://github.com/user-attachments/assets/f84406bb-0d27-4da6-b8f1-6db43b1fe360" />
