### ISSUE TITLE
add propertyPath for 422 response body

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#278]
a/c:

- 422 response body should follow the following format
  - [
  {
    "reason": "string",
    "message": "string",
    "referenceError": "string",
    "code": "missingProperty",
    "propertyPath": "string"
  }
]
- the path of the error property should be put into "propertyPath"

**Comment by cheng0504** [comment]
pass the 422 code format:
<img width="804" alt="Image" src="https://github.com/user-attachments/assets/dd99b0fb-702b-4db5-a265-95b93f9e4b63" />
