### ISSUE TITLE
convert all 400 status code for request validation into 422

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#279]
a/c:

- convert all 400 for request validation into 422
- code in response should be
   - missingProperty: The property the Seller has expected is not present in the payload
   - invalidValue: The property has an incorrect value
   - invalidFormat: The property value does not comply with the expected value format

**Comment by cheng0504** [comment]
missingProperty: The property the Seller has expected is not present in the payload
<img width="765" alt="Image" src="https://github.com/user-attachments/assets/039965c4-5d9e-450c-8a46-aa025dadff20" />
invalidValue: The property has an incorrect value
<img width="731" alt="Image" src="https://github.com/user-attachments/assets/ab523490-3e1a-4c03-a020-fa26675d42eb" />

**invalidFormat:** The property value does not comply with the expected value format
<img width="761" alt="Image" src="https://github.com/user-attachments/assets/dcdaf85d-0ea9-4242-a5b0-d8ed1978f4c4" />

**Comment by cheng0504** [comment]
giving Integer but expected String, should return ** invalidFormat**
but now it is invalidValue

**Comment by cheng0504** [comment]
productRelationship.id not present  --- missingProperty
productRelationship.id = "" -- invalidValue
productRelationship.id = null  --

**Comment by cheng0504** [comment]
productRelationship.id not present  --- missingProperty
productRelationship.id = "" -- invalidValue
productRelationship.id = null  --

**Comment by cheng0504** [comment]
<img width="824" alt="Image" src="https://github.com/user-attachments/assets/9e160b4e-8a45-403e-b729-aaec388e3ccf" />

**Comment by cheng0504** [comment]
@xuelianhan007 
order-uni-keyname = null
<img width="821" alt="Image" src="https://github.com/user-attachments/assets/95f88266-30ff-4ecc-894a-feeacb7bdb6b" />

**Comment by cheng0504** [comment]
keyname = 1, string expected
<img width="814" alt="Image" src="https://github.com/user-attachments/assets/b07b9bb6-b019-4754-b189-8d36731b18f1" />
