### ISSUE TITLE
[BUG] sonata property should not be editable when customizedField is false in mapping template

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#282]
**Describe the bug**
In request and response mapping of one sonata use case, right now sonata property is editable when customizedField is false in mapping template

**Expected behavior**
- sonata property should not be editable when customizedField is false in mapping template
- this rule can be applied to both request and response mapping

**Screenshots**
![Screen Shot 2024-12-06 at 3 22 45 PM](https://github.com/user-attachments/assets/657c4d2c-7442-446e-8c12-b712facf3898)

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/760ca180-f506-472c-aa01-8944cc53f050)
non customer defined value is not modifiable.
