### ISSUE TITLE
[BUG] [FE] always failed yaml validation for the uploaded api spec when creating a seller API in linux laptop

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#284]
**Describe the bug**
login control plane portal through a browser in linux laptop, when user is trying to create a new seller api server and upload a yaml api spec, it always failed the yaml validation while it works in mac.

**To Reproduce**
1. Go to 'Seller API server' and try to create a new seller api server
2. upload the api spec
3. FE always pops up "Please upload valid api spec in yaml format"

**Expected behavior**
pass validation and create the server successfull

**Screenshots**
![Image](https://github.com/user-attachments/assets/9def747c-e0da-4777-a97f-64a80b16b26b)

**Comment by cheng0504** [comment]
upload ymal file success, but clicking 'view' button, there is an error
![Image](https://github.com/user-attachments/assets/4993a16a-73ff-4dca-abfe-d24af6fe9913)

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/3f642c3f-bd5d-43a3-b28d-c666f38a1dc4)

**Comment by miyaflowercat** [comment]
view issue can be tracked through another ticket.
