### ISSUE TITLE
[mapping template] [request property type check] Create ELine add quote

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#289]
a/c:

- support adding property type validation for Create ELine add quote

**Comment by cheng0504** [comment]
quoteItem[].product.productRelationship[0].id
<img width="708" alt="Image" src="https://github.com/user-attachments/assets/a3e4e412-5d8b-4bad-b029-64b22224d813" />
@{{quoteItem[0].requestedQuoteItemTerm.duration.amount}}
<img width="741" alt="Image" src="https://github.com/user-attachments/assets/be961429-9bf0-4da5-a86b-37f85913d2cf" />
@{{quoteItem[0].product.place[0].id}}
<img width="753" alt="Image" src="https://github.com/user-attachments/assets/d3834ae4-f559-4321-861b-8ecf435743d5" />
@{{quoteItem[0].product.productConfiguration.bandwidth}}
<img width="788" alt="Image" src="https://github.com/user-attachments/assets/e2179d7d-e593-44cc-8b82-c6c59d37ee4a" />
@{{quoteItem[0].product.productConfiguration.classOfService}}
<img width="755" alt="Image" src="https://github.com/user-attachments/assets/937d31da-4d12-4627-b91a-b1bec6f2ffd3" />
@{{quoteItem[0].product.productConfiguration.paymentType}}
<img width="813" alt="Image" src="https://github.com/user-attachments/assets/77918a50-3418-4337-b181-931c19f202c7" />
<img width="745" alt="Image" src="https://github.com/user-attachments/assets/54008e8e-c4ee-4ea6-9c61-7a11e5ad5afc" />
@{{quoteItem[0].product.productOffering.id}}
<img width="763" alt="Image" src="https://github.com/user-attachments/assets/aaaf4a0f-e350-4b04-b08c-984e76e2697e" />
