### ISSUE TITLE
[FEATURE] [control plane] new home page - quick start guide

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#29]
a/c:

- able to track if user has completed some key activities on the platform
   - register one seller API server
   - complete one API mapping use case
       - there are more than 2 use cases in the list in complete state (2 are in complete by default)
   - deploy one use case to stage data plane
   - register one buyer
   - deploy one stage deployed use case to production

**Comment by cheng0504** [comment]
passed except
![Image](https://github.com/user-attachments/assets/fa11897d-ef06-4e0e-80e2-0269810286a3)
tracked by https://github.com/mycloudnexus/kraken/issues/19
