### ISSUE TITLE
[mapping template] [request property type check] Create UNI add order and create Eline ADD order

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#290]
a/c:

- property type was added to mapping template
- property type validation is checked after receiving request

**Comment by cheng0504** [comment]
<img width="826" alt="Image" src="https://github.com/user-attachments/assets/005117ea-ac21-4bdb-9cdd-aa08308045ed" />

**Comment by cheng0504** [comment]
need to add exist check for request validation
![Image](https://github.com/user-attachments/assets/f3112d98-0226-4565-87c5-19698ebcf0fc)

@xuelianhan007

**Comment by cheng0504** [comment]
<img width="822" alt="Image" src="https://github.com/user-attachments/assets/3aa52cb4-84f9-4e80-ac0e-54cf4a753acd" />
<img width="824" alt="Image" src="https://github.com/user-attachments/assets/574ae2be-1b5b-409b-98c1-b0f3ed5aea42" />

**Comment by cheng0504** [comment]
<img width="816" alt="Image" src="https://github.com/user-attachments/assets/a37bffa3-e08a-4071-8b24-39a26b5abe8a" />
<img width="852" alt="Image" src="https://github.com/user-attachments/assets/06fd71db-7d12-4672-a10b-a261f04d868c" />

**Comment by cheng0504** [comment]
eline name
<img width="828" alt="Image" src="https://github.com/user-attachments/assets/d526f8e1-82fd-4c71-bf0c-5e7659b58fd6" />
<img width="841" alt="Image" src="https://github.com/user-attachments/assets/be6b01cc-c4f8-4b84-958d-8629e816c0b8" />
<img width="849" alt="Image" src="https://github.com/user-attachments/assets/3f90b08b-875b-42c0-81c8-330697c28bff" />

**Comment by cheng0504** [comment]
paymenttype
<img width="803" alt="Image" src="https://github.com/user-attachments/assets/612117a7-2865-43c7-bfd4-123bd8be8156" />

**Comment by cheng0504** [comment]
<img width="824" alt="Image" src="https://github.com/user-attachments/assets/762fd773-2b50-49ba-b529-6d339a918116" />
