### ISSUE TITLE
[mapping template] [request property type check] Create UNI DELETE order and create Eline DELETE order

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#293]
a/c:

- for Create UNI DELETE order and create Eline DELETE order
   - request property type are added into template

**Comment by cheng0504** [comment]
uni
<img width="804" alt="Image" src="https://github.com/user-attachments/assets/f3267853-6be1-4a44-bc2b-b208f48d8ab0" />
<img width="840" alt="Image" src="https://github.com/user-attachments/assets/5f4bf79f-8785-434f-8db0-46c26b1ca223" />
<img width="828" alt="Image" src="https://github.com/user-attachments/assets/15208f6c-a2bf-4317-b0a4-e994b8e368aa" />
<img width="826" alt="Image" src="https://github.com/user-attachments/assets/285b5785-da15-4687-8713-55148abc354c" />
<img width="830" alt="Image" src="https://github.com/user-attachments/assets/44c0a3ea-a405-4cae-b0bf-cc27f2c02864" />
<img width="845" alt="Image" src="https://github.com/user-attachments/assets/a7f68608-9235-4178-aaa1-8029c9a62bc6" />
<img width="843" alt="Image" src="https://github.com/user-attachments/assets/62d44acc-37e2-40a2-85eb-881d02c3f99e" />

**Comment by cheng0504** [comment]
eline
<img width="816" alt="Image" src="https://github.com/user-attachments/assets/b886b0d9-c08a-4748-bc64-16a9eb42395d" />
<img width="792" alt="Image" src="https://github.com/user-attachments/assets/88745abf-2d50-4b3a-ada8-12490d3864c3" />
<img width="822" alt="Image" src="https://github.com/user-attachments/assets/ea301ce9-6c3c-4355-9af4-11c15d7e6098" />
<img width="820" alt="Image" src="https://github.com/user-attachments/assets/37b47595-fd06-44e8-8311-2a797ff05343" />
<img width="818" alt="Image" src="https://github.com/user-attachments/assets/94a762d3-b566-4c5d-a0c8-27f8dc0f7518" />
<img width="815" alt="Image" src="https://github.com/user-attachments/assets/0386ea0c-a0fb-4fd6-a172-4e399241f4ff" />
<img width="844" alt="Image" src="https://github.com/user-attachments/assets/425aff0c-d576-497f-a534-d57aff51be55" />
