### ISSUE TITLE
[Improvement] All the properties from predefined mapping template should not be editable and shown as read-only form

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#299]
**Describe the issues**
<img width="1502" alt="image" src="https://github.com/user-attachments/assets/619257cb-b297-4e30-9a67-3b60be57634b" />

**Describe the expectation**
<img width="1998" alt="image" src="https://github.com/user-attachments/assets/903a81de-2566-47e4-9431-d06e7ca87022" />

**Comment by miyaflowercat** [comment]
The pre-defined properties are not editable now,  but the hover over to show full value is not supported.
<img width="1247" alt="Image" src="https://github.com/user-attachments/assets/a30322b0-9aa7-4bc3-8e24-237a134851a3" />

**Comment by emmawu001** [comment]
Yeah, the tooltip for the overflowed property is lost. Need to fix this.

**Comment by cheng0504** [comment]
the layout of right side between request and response is not matched.
Request: doesn't have field grey on editable fields
![Image](https://github.com/user-attachments/assets/785109c3-4e07-4462-af5a-cc1e6c5a9805)
Response:has field grep on editable fields
![Image](https://github.com/user-attachments/assets/267fc6d0-c120-4ac3-a72f-a58acf1f1574)
