### ISSUE TITLE
[FEATURE] Mapping Template Upgrade - version list

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#30]
As a user of kraken control plane, I would be able to view a list of mapping template versions that released together with kraken and I can 
- view release notes of each version
- upgrade to a "not upgraded" version
- view upgrade progress of each plane
- check pre-condition for stage data plane upgrade
- check pre-condition for production data plane upgrade

**Comment by kuangxiang20240501** [comment]
Endpoint :check pre-condition for stage data plane upgrade -- when click next button in stage data plane upgtade 

- url 
  - check pre-condition for stage data plane upgrade
- request
  - `curl --location 'http://localhost:8001/v3/products/:productId/template-upgrade/stage-upgrade-check?templateUpgradeId=671bdcb1-29e4-4d8b-8161-4325898702c1&envId=2fd92244-a8d1-43fc-b76d-d87ffb0172f4' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer XXX'`

- response
  - `{
    "code": 200,
    "message": "OK",
    "data": [
        "This mapping template is deprecated.A newer version mapping template started to upgrade."
    ]
}`

**Comment by kuangxiang20240501** [comment]
Endpoint :check pre-condition for production data plane upgrade -- when click next button in production data plane upgtade

- url
  - /v3/products/{productId}/template-upgrade/production-upgrade-check

- request
  - `curl --location 'http://localhost:8001/v3/products/mef.sonata/template-upgrade/production-upgrade-check?templateUpgradeId=671bdcb1-29e4-4d8b-8161-4325898702c1&envId=2fd92244-a8d1-43fc-b76d-d87ffb0172f4' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer XXX'`

- response
   -`{
    "code": 200,
    "message": "OK",
    "data": [
        "error environment: not production environment",
        "This mapping template is deprecated.A newer version mapping template started to upgrade."
    ]
}`

**Comment by kuangxiang20240501** [comment]
Endpoint: list all of template upgrade records

- url
`/v3/products/:productId/template-upgrade/releases`
- parameter
  - templateUpgradeId

- request
```
curl --location 'https://external-kraken-mgmt.dev.consolecore.io/v3/products/mef.sonata/template-upgrade/releases?templateUpgradeId=33dea20e-3f0f-45a1-8fc2-5914742e5b8f' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer XXX'
```
- response
```json
{
    "code": 200,
    "message": "OK",
    "data": {
        "data": [
            {
                "templateUpgradeId": "33dea20e-3f0f-45a1-8fc2-5914742e5b8f",
                "name": "V1.5.2",
                "productVersion": "V1.5.2",
                "productSpec": "grace",
                "publishDate": "2024-10-28",
                "description": "Refactor the error tips for quote detail, order detail and inventory list page.\n",
                "deployments": [
                    {
                        "deploymentId": "a1eddb33-86ec-4c14-b5cb-5a008799829a",
                        "templateUpgradeId": "33dea20e-3f0f-45a1-8fc2-5914742e5b8f",
                        "envName": "CONTROL_PLANE",
                        "productVersion": "V1.5.2",
                        "upgradeBy": "e5543373-8e30-4e00-b6d1-cf95495de9c7",
                        "status": "SUCCESS",
                        "createdAt": "2024-10-31T09:37:25.37783Z",
                        "updatedAt": "2024-10-31T09:37:29.822971Z"
                    },
                    {
                        "deploymentId": "57e601e3-e912-47bb-8c00-40d08c6ecad3",
                        "templateUpgradeId": "33dea20e-3f0f-45a1-8fc2-5914742e5b8f",
                        "envName": "stage",
                        "productVersion": "V1.5.2",
                        "upgradeBy": "07b7e2e6-3f1c-4dc2-a7b0-9ff1c8324b5f",
                        "status": "SUCCESS",
                        "createdAt": "2024-10-30T05:46:55.575115Z",
                        "updatedAt": "2024-10-30T05:47:42.527726Z"
                    }
                ],
                "showStageUpgradeButton": false,
                "showProductionUpgradeButton": false,
                "status": "Upgrading"
            }
        ],
        "total": 1,
        "page": 0,
        "size": 20
    }
}
```
