### ISSUE TITLE
[Improvement][control plane][FE] check duplicate name when creating a new seller API server

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#32]
a/c:

- In seller api server creation page, check if the name is used or not after user inputs a name and press enter
- if it is used, report error under the input box

**Comment by miyaflowercat** [comment]
Request:

curl -X 'GET' \
  '{{baseurl}}/v2/products/mef.sonata/components/mef.sonata/api-servers/test-1022' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer login-token-here' 
Response:

```
{
  "code": 200,
  "message": "The API Server name has existed:test-1022",
  "data": false
} 
```
If the Server name was the first time to use, then the response body is as following:

```
{
  "code": 200,
  "message": "OK",
  "data": true
}
```

**Comment by cheng0504** [comment]
pass

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/c708cfac-2b8b-413d-ab1c-8da3db951b8e)
