### ISSUE TITLE
[control plane][BE] return buyer company id and name in api activity log

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#33]
a/c:

- return the buyer company id and name who triggered the sonata api request in api activity log for each record

**Comment by cheng0504** [comment]
tested with pass
![Image](https://github.com/user-attachments/assets/d1b74b54-fd77-4ab3-b817-86869ef19d52)

**Comment by cheng0504** [comment]
buyer: uuid

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/aeda7539-d84f-4928-8179-8da207bb3873)
pass
