### ISSUE TITLE
[BUG] one buyer token can be only used in associated data plane

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#35]
**Describe the bug**
stage buyer token can be used in production and vice versa.

**Expected behavior**
one buyer token can be only used in associated data plane

**Screenshots**
n/a

**Additional context**
n/a

**Comment by cheng0504** [comment]
I use prod x-kraken-key token in staging env, still can send out api and get response.
![Image](https://github.com/user-attachments/assets/dd4298f6-02f2-4bd9-b5e1-7ce401cf506c)

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/c4c07997-4894-4134-b3f5-f938932d2f5f)
