### ISSUE TITLE
[mapping template]typo fix for create Eline add order template

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#37]
**Describe the bug**
some "UNI" in property title in create eline add order template should be changed to "Eline"

**To Reproduce**
- check in mapping page

**Expected behavior**
some "UNI" in property title in create eline add order template should be changed to "Eline"

**Screenshots**

**Additional context**
n/a

**Comment by cheng0504** [comment]
@zhiyaoPCCW 
still 2 UNI found in title and name
![Image](https://github.com/user-attachments/assets/ce001c95-9100-43ef-a75a-a2a2b31492ad)

**Comment by cheng0504** [comment]
after discussion, these 2 fields are for srcUni and destUni
tested with pass.
