### ISSUE TITLE
[BUG] [BE] Uni Add Order - need to add role = INSTALL_LOCATION value check

### ISSUE THREAD

**Issue by cheng0504** [mycloudnexus/kraken#38]
Currently Uni Add Order doesn't have value check for place.role.
We should only support role = INSTALL_LOCATION, but now user can fill in anything.
Expected:
add role = INSTALL_LOCATION value check
<img width="601" alt="image" src="https://github.com/user-attachments/assets/fc5106bc-5969-434d-944c-4d8ad411a5b0">

**Comment by cheng0504** [comment]
pay load:
curl --location 'https://api.consoleconnect.com/Sonata/staging/mefApi/sonata/productOrderingManagement/v10/productOrder?buyerId=qe1company' \
--header 'Content-Type: application/json' \
--header 'Cookie: plb=7f8597cbdd145f9e; plb=7f8597cbdd145f9e' \
--data-raw '{
    "note": [],
    "relatedContactInformation": [
        {
            "number": "111 222 333",
            "emailAddress": "productOrderContact@mef.com",
            "role": "productOrderContact",
            "postalAddress": null,
            "organization": "MEF",
            "name": "Joe Order",
            "numberExtension": null
        }
    ],
    "externalId": "AEL[9301] General On-net Order ",
    "projectId": "MEF OIT",
    "productOrderItem": [
        {
            "relatedBuyerPON": null,
            "note": [],
            "product": {
                "productOffering": {
                    "href": null,
                    "id": "UNI"
                },
                "productConfiguration": {
                    "@type": "UNI",
                    "bandwidth": 1000,
                    "bandwidthUnit": "MBPS",
                     "name" : "test-qc01",
                    "paymentType" : "invoice"
                },
                "productRelationship": [],
                "id": null,
                "href": null,
                "place": [
                    {
                        "role": "INSTALL_LOCATION1",
                        "href": null,
                        "id": "qe-dcf-1",
                        "@type": "GeographicAddressRef",
                        "@schemaLocation": null
                    }
                ]
            },
            "relatedContactInformation": [
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.ProductOrderItemContact@mef.com",
                    "role": "buyerProductOrderItemContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Product Order Item Contact",
                    "numberExtension": null
                },
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.ImplementationContact@mef.com",
                    "role": "buyerImplementationContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Implementation Contact",
                    "numberExtension": null
                },
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.TechnicalContact@mef.com",
                    "role": "buyerTechnicalContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Technical Contact ",
                    "numberExtension": null
                },
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.ItemServiceSiteContact@mef.com",
                    "role": "orderItemServiceSiteContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Technical Contact ",
                    "numberExtension": null
                }
            ],
            "requestedItemTerm": {
                "name": "UNI Item Term",
                "duration": {
                    "amount": 1,
                    "units": "calendarMonths"
                },
                "endOfTermAction": "roll",
                "rollInterval": {
                    "amount": 1,
                    "units": "calendarMonths"
                }
            },
            "billingAccount": {
                "id": "001"
            },
            "productOrderItemRelationship": [],
            "tspRestorationPriority": null,
            "productOfferingQualificationItem": {
                "productOfferingQualificationId": "",
                "alternateProductProposalId": null,
                "productOfferingQualificationHref": null,
                "id": "UNI"
            },
            "coordinatedAction": [],
            "action": "add",
            "quoteItem": {
                "quoteHref": null,
                "id": "UNI",
                "quoteId": "fefc66b7-cfc4-426d-a55a-d05c41b82acf"
            },
            "endCustomerName": null,
            "expediteIndicator": false,
            "id": "UNI",
            "requestedCompletionDate": "2121-11-30T23:00:00Z"
        }
    ]
}'

**Comment by cheng0504** [comment]
@xuelianhan007 looks like the current error message is not as our expectation?
checking value: "role": "INSTALL_LOCATION"
![Image](https://github.com/user-attachments/assets/02eb848a-0486-4618-a2c5-63ec817e6640)

**Comment by xuelianhan007** [comment]
![Image](https://github.com/user-attachments/assets/4fc8c563-ac90-40cf-925e-baebc91424c2)
![Image](https://github.com/user-attachments/assets/186dab34-0c93-4373-b219-d0fedd91dbbb)

**Comment by cheng0504** [comment]
uni order add:
INSTALL_LOCATION - not existed
![image](https://github.com/user-attachments/assets/2cbc57c1-3e9d-4958-81a6-0cc3e69d2973)

**Comment by cheng0504** [comment]
for UNI: pass
![Image](https://github.com/user-attachments/assets/3324b95f-af70-4eb7-b3dc-9fa7b5fa2b87)
![Image](https://github.com/user-attachments/assets/aad4e96f-1dbe-4fec-9acf-65a5722786e3)
