### ISSUE TITLE
[BUG] [BE] Uni Add order: need to add value check:  "@type": "GeographicAddressRef",

### ISSUE THREAD

**Issue by cheng0504** [mycloudnexus/kraken#39]
Similar with bug 27, need to add value check for input value of place.type.
Only support "@type": "GeographicAddressRef".
<img width="502" alt="image" src="https://github.com/user-attachments/assets/37f3ac4e-5db8-4e1e-b5f9-b299d919a7a3">

<img width="538" alt="image" src="https://github.com/user-attachments/assets/50c6665d-13fb-426c-9497-6de6c0256494">

Expected: add value check for input value place.type == "GeographicAddressRef"

**Comment by cheng0504** [comment]
pay load
curl --location 'https://api.consoleconnect.com/Sonata/staging/mefApi/sonata/productOrderingManagement/v10/productOrder?buyerId=qe1company' \
--header 'Content-Type: application/json' \
--header 'Cookie: plb=7f8597cbdd145f9e; plb=7f8597cbdd145f9e' \
--data-raw '{
    "note": [],
    "relatedContactInformation": [
        {
            "number": "111 222 333",
            "emailAddress": "productOrderContact@mef.com",
            "role": "productOrderContact",
            "postalAddress": null,
            "organization": "MEF",
            "name": "Joe Order",
            "numberExtension": null
        }
    ],
    "externalId": "AEL[9301] General On-net Order ",
    "projectId": "MEF OIT",
    "productOrderItem": [
        {
            "relatedBuyerPON": null,
            "note": [],
            "product": {
                "productOffering": {
                    "href": null,
                    "id": "UNI"
                },
                "productConfiguration": {
                    "@type": "UNI",
                    "bandwidth": 1000,
                    "bandwidthUnit": "MBPS",
                     "name" : "test-qc01",
                    "paymentType" : "invoice"
                },
                "productRelationship": [],
                "id": null,
                "href": null,
                "place": [
                    {
                        "role": "INSTALL_LOCATION",
                        "href": null,
                        "id": "qe-dcf-1",
                        "@type": "GeographicAddressRef1",
                        "@schemaLocation": null
                    }
                ]
            },
            "relatedContactInformation": [
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.ProductOrderItemContact@mef.com",
                    "role": "buyerProductOrderItemContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Product Order Item Contact",
                    "numberExtension": null
                },
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.ImplementationContact@mef.com",
                    "role": "buyerImplementationContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Implementation Contact",
                    "numberExtension": null
                },
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.TechnicalContact@mef.com",
                    "role": "buyerTechnicalContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Technical Contact ",
                    "numberExtension": null
                },
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.ItemServiceSiteContact@mef.com",
                    "role": "orderItemServiceSiteContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Technical Contact ",
                    "numberExtension": null
                }
            ],
            "requestedItemTerm": {
                "name": "UNI Item Term",
                "duration": {
                    "amount": 1,
                    "units": "calendarMonths"
                },
                "endOfTermAction": "roll",
                "rollInterval": {
                    "amount": 1,
                    "units": "calendarMonths"
                }
            },
            "billingAccount": {
                "id": "001"
            },
            "productOrderItemRelationship": [],
            "tspRestorationPriority": null,
            "productOfferingQualificationItem": {
                "productOfferingQualificationId": "",
                "alternateProductProposalId": null,
                "productOfferingQualificationHref": null,
                "id": "UNI"
            },
            "coordinatedAction": [],
            "action": "add",
            "quoteItem": {
                "quoteHref": null,
                "id": "UNI",
                "quoteId": "fefc66b7-cfc4-426d-a55a-d05c41b82acf"
            },
            "endCustomerName": null,
            "expediteIndicator": false,
            "id": "UNI",
            "requestedCompletionDate": "2121-11-30T23:00:00Z"
        }
    ]
}'

**Comment by miyaflowercat** [comment]
seems like still not working

**Comment by xuelianhan007** [comment]
![image](https://github.com/user-attachments/assets/359e1906-3de6-4439-a0c1-43cf1d2f047b)

**Comment by cheng0504** [comment]
for UNI: pass
![Image](https://github.com/user-attachments/assets/13f3d24e-7cdc-4703-99ed-f0db6575c86f)
![Image](https://github.com/user-attachments/assets/e0ceba20-df3c-43e5-9588-20946f101cc7)
