### ISSUE TITLE
[FEATURE] Enable SonarCloud code analysis

### ISSUE THREAD

**Issue by DaveXiong** [mycloudnexus/kraken#4]
Pls help to enable sonarcloud code analysis for this repo, and config it as the automatic analysis at the moment.

**Comment by RyanDinglei** [comment]
Have added the credentials to the repo: SONAR_TOKEN

**Comment by RyanDinglei** [comment]
Update pom.xml file with the following properties:
`<properties>
  <sonar.organization>mycloudnexus</sonar.organization>
  <sonar.host.url>https://sonarcloud.io</sonar.host.url>
</properties>`

**Comment by RyanDinglei** [comment]
Have imported the repo to sonar cloud. https://sonarcloud.io/project/overview?id=mycloudnexus_kraken and se the analysis method to automatic for now,

**Comment by DaveXiong** [comment]
Thanks, sonarcloud already can report the scan result to pull requests:
![image](https://github.com/user-attachments/assets/9b4ede1d-9412-417d-bde4-bcc8a0057b76)

**Comment by DaveXiong** [comment]
all good now
