### ISSUE TITLE
[BUG] eline add order - value check for productOrderItem[0].product.productRelationship[0].relationshipType

### ISSUE THREAD

**Issue by cheng0504** [mycloudnexus/kraken#40]
the following 2 parameters don't have value check:
productOrderItem[0].product.productRelationship[0].relationshipType  == CONNECTS_TO_ENNI
-- | --
productOrderItem[0].product.productRelationship[1].relationshipType  == CONNECTS_TO_UNI

<img width="654" alt="image" src="https://github.com/user-attachments/assets/3863138f-5a5a-47ce-87eb-357dabff5737">

Expected result:
need to add value check for productRelationship[*].relationshipType

**Comment by cheng0504** [comment]
pay load
--
curl --location 'https://api.consoleconnect.com/Sonata/staging/mefApi/sonata/productOrderingManagement/v10/productOrder?buyerId=qe1company' \
--header 'Content-Type: application/json' \
--header 'Cookie: plb=7f8597cbdd145f9e; plb=7f8597cbdd145f9e' \
--data-raw '{
    "note": [],
    "relatedContactInformation": [
        {
            "number": "111 222 333",
            "emailAddress": "productOrderContact@mef.com",
            "role": "productOrderContact",
            "postalAddress": null,
            "organization": "MEF",
            "name": "Joe Order",
            "numberExtension": null
        }
    ],
    "externalId": "AEL[9301] General On-net Order ",
    "projectId": "MEF OIT",
    "productOrderItem": [
        {
            "relatedBuyerPON": null,
            "note": [],
            "product": {
                "productOffering": {
                    "href": null,
                    "id": "ACCESS_E_LINE"
                },
                "productConfiguration": {
                    "@type": "ACCESS_E_LINE",
                    "bandwidth": 1,
                    "bandwidthUnit": "MBPS",
                   "classOfService": "SILVER",
                  "paymentType": "invoice",
"name": "Qe 1 Company Connection 0904",
"buyerCompanyId": "qe1company",
"destUNIMetroId": "5db65dcf5d545c000bc6884b",
"type": "LAYER2"
                },
                "productRelationship": [
                    {
                        "relationshipType": "CONNECTS_TO_ENNI0",
                        "id": "6371e5fa2fb2fa00155a3535",
                        "href": null
                    },
                    {
                        "relationshipType": "CONNECTS_TO_UNI1",
                        "id": "63634cbf11ffdd00151fc6fb",
                        "href": null
                    }
                ],
                "id": null,
                "href": null,
                "place": []
            },
            "relatedContactInformation": [
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.ProductOrderItemContact@mef.com",
                    "role": "buyerProductOrderItemContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Product Order Item Contact",
                    "numberExtension": null
                },
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.ImplementationContact@mef.com",
                    "role": "buyerImplementationContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Implementation Contact",
                    "numberExtension": null
                },
                {
                    "number": "+12-345-678-90",
                    "emailAddress": "Buyer.TechnicalContact@mef.com",
                    "role": "buyerTechnicalContact",
                    "postalAddress": null,
                    "organization": null,
                    "name": "Buyer Technical Contact ",
                    "numberExtension": null
                }
            ],
            "requestedItemTerm": {
                "name": "ELine Item Term",
                "duration": {
                    "amount": 1,
                    "units": "calendarMonths"
                },
                "endOfTermAction": "roll",
                "rollInterval": {
                    "amount": 1,
                    "units": "calendarMonths"
                }
            },
            "billingAccount": {
                "id": "001"
            },

            "tspRestorationPriority": null,
            "productOfferingQualificationItem": {
                "productOfferingQualificationId": "",
                "alternateProductProposalId": null,
                "productOfferingQualificationHref": null,
                "id": "ELINE"
            },
            "coordinatedAction": [],
            "action": "add",
            "quoteItem": {
                "quoteHref": null,
                "id": "ELINE",
                "quoteId": "fefc66b7-cfc4-426d-a55a-d05c41b82acf"
            },
            "endCustomerName": null,
            "expediteIndicator": false,
            "id": "ELINE",
            "requestedCompletionDate": "2121-11-30T23:00:00Z"
        }
    ]
}'

**Comment by cheng0504** [comment]
@xuelianhan007 this issue still existed
![Image](https://github.com/user-attachments/assets/11748a71-bbc2-4262-8a9d-5f8314cad448)

**Comment by xuelianhan007** [comment]
![image](https://github.com/user-attachments/assets/540bdcef-6390-45ac-99be-81ef085e4078)
![image](https://github.com/user-attachments/assets/7163f805-700c-41ec-a47c-435fc2199ab6)

**Comment by cheng0504** [comment]
for eline: pass
![Image](https://github.com/user-attachments/assets/510d9713-b9b7-4591-873d-8df555249fa5)
![Image](https://github.com/user-attachments/assets/b72bfdab-bcfb-4c6a-bb62-25d8bf131b05)
![Image](https://github.com/user-attachments/assets/90b12bf9-1179-42ff-ba5c-c6cad25a50e7)
![Image](https://github.com/user-attachments/assets/6e67bbc0-dbd7-4570-aaaa-c5b9521630c0)
