### ISSUE TITLE
[BUG] no api activities when user set start date and end date to the same day

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#42]
**Describe the bug**
when user is trying to search api activities by time range, no api activities when user set start date and end date to the same day even though it has data.

**To Reproduce**
n/a

**Expected behavior**
when user set the start date and end date to the same day, it should show api activities of that day.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by cheng0504** [comment]
passed
![Image](https://github.com/user-attachments/assets/1b597d3e-030f-4e7f-92ef-78ccefe3ac0f)
