### ISSUE TITLE
[BUG] [BE] UNI/Eline Get Order by id - R29 and R48 Check about state and completionDate/expectedCompletionDate

### ISSUE THREAD

**Issue by cheng0504** [mycloudnexus/kraken#43]
productOrderItem.expectedCompletionDate check in response:
`pm.test("[R29] If the Product Order Item state in the Seller's response is not completed, the response MUST contain the expectedCompletionDate.", 
function () {
    _.each(response.productOrderItem, (item) => {
        if(item.state != "completed"){
            pm.expect(item.expectedCompletionDate != null).to.be.true
        }
    })
});`
productOrderItem.completionDate check in response:
`pm.test("[R48] If the Product Order Item state in the Seller's response is completed, the response MUST contain the completionDate attribute." +
        "[R49] If the Product Order Item state in the Seller's response is not completed, the response MUST NOT contain the completionDate attribute.", 
function () {
    _.each(response.productOrderItem, (item) => {
        if(item.state === "completed"){
            pm.expect(item.completionDate != null).to.be.true
        }
        if(item.state != "completed"){
            pm.expect(item.completionDate === null).to.be.true
        }
    })
});`

<img width="691" alt="image" src="https://github.com/user-attachments/assets/ed85fb92-421a-4f99-90fa-009b5fbd9fb6">

**Comment by cheng0504** [comment]
current response for uni get order
`{
    "id": "22c8a578-92e9-44ba-bda7-9b3bd46f574b",
    "relatedContactInformation": [
        {
            "name": "Joe Order",
            "role": "productOrderContact",
            "number": "111 222 333",
            "emailAddress": "productOrderContact@mef.com"
        },
        {
            "number": "N/A",
            "emailAddress": "support@consoleconnect.com",
            "role": "sellerContact",
            "name": "consoleconnect"
        }
    ],
    "productOrderItem": [
        {
            "action": "add",
            "id": "UNI",
            "product": {
                "productOffering": {
                    "id": "UNI"
                },
                "productConfiguration": {
                    "name": "test-qc01",
                    "@type": "UNI",
                    "bandwidth": 1000,
                    "paymentType": "invoice",
                    "bandwidthUnit": "MBPS"
                },
                "place": [
                    {
                        "id": "qe-dcf-1",
                        "role": "INSTALL_LOCATION",
                        "@type": "GeographicAddressRef"
                    }
                ]
            },
            "requestedItemTerm": {
                "name": "UNI Item Term",
                "duration": {
                    "units": "calendarMonths",
                    "amount": 1
                },
                "rollInterval": {
                    "units": "calendarMonths",
                    "amount": 1
                },
                "endOfTermAction": "roll"
            },
            "state": "allocated"
        }
    ],
    "orderDate": "2024-10-30 07:19:53",
    "state": "allocated",
    "orderId": "6721de1cba423681d6bc34ba",
    "completionDate": "2024-10-30T07:20:09.158Z",
    "instanceId": ""
}`

**Comment by miyaflowercat** [comment]
close as fixed in another ticket.
