### ISSUE TITLE
[BUG] [BE]UNI/Eline get order by id - structure check for productOrderItem(status change) and response object based on "state"

### ISSUE THREAD

**Issue by cheng0504** [mycloudnexus/kraken#44]
pm.test("[R62] The Seller's response MUST comply with the states and attributes detailed in Table 10 and Table 11.", function () {
    var sellerContactInformation = response.relatedContactInformation.find(function(element){
        return element.role === "sellerContact"
    })

        if(response.state === "acknowledged" 
            || response.state === "assessingCancellation" 
            || response.state === "held.assessingCharge"
            || response.state === "inProgress"
            || response.state === "pendingCancellation"){
            pm.expect(response.id !=null).to.be.true
            pm.expect(response.orderDate !=null).to.be.true
            pm.expect(response.state !=null).to.be.true
            pm.expect(sellerContactInformation !=null).to.be.true
        }
        if(response.state === "cancelled"){
            pm.expect(response.id !=null).to.be.true
            pm.expect(response.orderDate !=null).to.be.true
            pm.expect(response.state !=null).to.be.true
            pm.expect(sellerContactInformation !=null).to.be.true
            pm.expect(cancellationReason !=null).to.be.true
            pm.expect(cancellationDate !=null).to.be.true
            pm.expect(completionDate !=null).to.be.true
        }
        if(response.state === "completed" 
            || response.state === "failed"
            || response.state === "partial"
            || response.state === "rejected"){
            pm.expect(response.id !=null).to.be.true
            pm.expect(response.orderDate !=null).to.be.true
            pm.expect(response.state !=null).to.be.true
            pm.expect(sellerContactInformation !=null).to.be.true
            pm.expect(response.completionDate !=null).to.be.true
        }
        // product order items
        _.each(response.productOrderItem, (item) => {
            var state= item.state;
            if(state === "acknowledged"){
                pm.expect(item.expediteAcceptedIndicator !=null).to.be.true
                pm.expect(item.stateChange !=null).to.be.true
                pm.expect(item.state !=null).to.be.true
            }
            if(state === "cancelled"){
                pm.expect(item.expediteAcceptedIndicator !=null).to.be.true
                pm.expect(item.stateChange !=null).to.be.true
                pm.expect(item.expectedCompletionDate !=null).to.be.true
                pm.expect(item.state !=null).to.be.true
                pm.expect(item.itemTerm !=null).to.be.true
            }
            if(state === "completed"){
                pm.expect(item.expediteAcceptedIndicator !=null).to.be.true
                pm.expect(item.stateChange !=null).to.be.true
                pm.expect(item.expectedCompletionDate !=null).to.be.true
                pm.expect(item.completionDate !=null).to.be.true
                pm.expect(item.state !=null).to.be.true
                pm.expect(item.itemTerm !=null).to.be.true
            }
            if(state === "failed"){
                pm.expect(item.expediteAcceptedIndicator !=null).to.be.true    
                pm.expect(item.stateChange !=null).to.be.true
                pm.expect(item.expectedCompletionDate !=null).to.be.true
                pm.expect(item.state !=null).to.be.true
                pm.expect(item.itemTerm !=null).to.be.true
                m.expect(item.terminationError !=null).to.be.true
            }
            if(state === "inProgress" 
                || state === "held" 
                || state === "pending"){
                pm.expect(item.expediteAcceptedIndicator !=null).to.be.true    
                pm.expect(item.stateChange !=null).to.be.true
                pm.expect(item.expectedCompletionDate !=null).to.be.true
                pm.expect(item.state !=null).to.be.true
                pm.expect(item.itemTerm !=null).to.be.true
            }
            if(state === "rejected"){
                pm.expect(item.expediteAcceptedIndicator !=null).to.be.true
                pm.expect(item.stateChange !=null).to.be.true
                pm.expect(item.state !=null).to.be.true
                pm.expect(item.itemTerm !=null).to.be.true
                pm.expect(item.terminationError !=null).to.be.true
            }
            if(state === "rejected.validated"){
                pm.expect(item.expediteAcceptedIndicator !=null).to.be.true
                pm.expect(item.stateChange !=null).to.be.true
                pm.expect(item.state !=null).to.be.true
                pm.expect(item.itemTerm !=null).to.be.true
            }
            if(state === "rejected.unassessed"){
                pm.expect(item.expediteAcceptedIndicator !=null).to.be.true
                pm.expect(item.stateChange !=null).to.be.true
                pm.expect(item.state !=null).to.be.true
            }
        })
});

**Comment by cheng0504** [comment]
so for response.state === "cancelled",  we need to add: 
response.cancellationReason !=null).to.be.true
response.cancellationDate !=null).to.be.true

**Comment by cheng0504** [comment]
for response. productOrderItem, need to have the following structure.
            pm.expect(item.expediteAcceptedIndicator !=null).to.be.true
            pm.expect(item.stateChange !=null).to.be.true
            pm.expect(item.expectedCompletionDate !=null).to.be.true
            pm.expect(item.itemTerm !=null).to.be.true

**Comment by miyaflowercat** [comment]
- need to update mapping template to add mapping for state of change
   - need to check with Amartus why they check stateChange
- cancelled state can be handled with cancel order support in the future
- need to request CC to support the mapping
