### ISSUE TITLE
[data plane][BE]Improve the tips of detail query for order and quote

### ISSUE THREAD

**Issue by xuelianhan007** [mycloudnexus/kraken#54]
Updating the error message for get order/quote by non-existing id and get product by non-existing 'productOrderId'.
Issue-1: The following message is not clear while an ID does not exist(or faked) being passed into the quote detail endpoint.

{
    "code": "notFound",
    "reason": "Asset not found,key=targetKey:notFound",
    "message": "time:Fri Oct 25 02:24:11 UTC 2024, error: Internal Server Error, path:/mefApi/sonata/quoteManagement/v8/quote/bd8ddf7a-9c28-4b83-9253-ce4e826549aa",
    "referenceError": "Asset not found,key=targetKey:notFound"
} 
The order detail  has the same issue.

The expected response should be as following:

{
  "code": "notFound",
  "reason": "order id or quote id does not exist",
  "message": "time:Fri Oct 25 02:24:11 UTC 2024, error: Internal Server Error, path:/mefApi/sonata/quoteManagement/v8/quote/bd8ddf7a-9c28-4b83-9253-ce4e826549aa",
  "referenceError": "order id or quote id does not exist"
}
 

Issue-2: For the inventory list endpoint,

getting product by productOrderId - when productOrderId is passed but does not exist, should not report 422(same with get order by non-existing id and get quote by non-existing id)

**Comment by cheng0504** [comment]
inventory list:
![Image](https://github.com/user-attachments/assets/14f0243f-0bfa-47bd-b2ee-39758fc04907)

**Comment by cheng0504** [comment]
pom - get:
![Image](https://github.com/user-attachments/assets/c6deafcc-87d5-4e39-86df-1d5331a3b562)

**Comment by cheng0504** [comment]
quote
![Image](https://github.com/user-attachments/assets/05560455-6370-4ecf-9364-075d26f46f68)
