### ISSUE TITLE
[FEATURE] [control plane][FE] display running api adapter/standard version /kraken version/upgrading status in the UI

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#60]
As a control plane user, I would like to understand the following information regarding the following information

- running api adapter name
- standard version
- kraken version
- mapping template upgrading status

**Comment by miyaflowercat** [comment]
url
`/system-info`
request
```
curl -X 'GET' \
  {{baseUrl}}/system-info' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer ' 
```
responses
```
{
  "code": 200,
  "message": "OK",
  "data": {
    "id": "1bba3aa0-6f40-4974-8e77-59674227f783",
    "createdAt": "2024-10-15T05:14:56.363035Z",
    "updatedAt": "2024-10-29T07:01:21.530939Z",
    "controlProductVersion": "V1.0",
    "stageProductVersion": "V1.5.1",
    "productionProductVersion": "V1.5.1",
    "controlAppVersion": "0.285.0",  // control plane kraken version which will show up in the tooltip
    "productKey": "mef.sonata", 
    "productSpec": "grace", // standard version
    "key": "CONTROL_PLANE",
    "status": "RUNNING",  //upgrading status, mapping template upgrading status
    "productionAppVersion": "0.284.0",  // production data plane kraken version which will show up in the UI and tooltip
    "stageAppVersion": "0.284.0" //stage data plane kraken version which will show up in the tooltip
  }
} 
```

status enum
```
CONTROL_PLANE_UPGRADING,
CONTROL_PLANE_UPGRADE_DONE,
STAGE_UPGRADING,
STAGE_UPGRADE_DONE,
PRODUCTION_UPGRADING,
RUNNING 
```

**Comment by kuangxiang20240501** [comment]
> @kuangxiang20240501 besides productKey, can we have productName with value of MEF LSO Sonata returned by BE? So that FE can pick it up, thanks.
Yeah,  I will reafactor the the code to support the case
> 
> Another thing is that can we support streaming data of this info as it impacts user's behavior significantly in the portal?
The front end can perform long polling to obtain the latest status where needed. The back end needs to bury points in multiple places to trigger push, which will lead to code coupling.

**Comment by kuangxiang20240501** [comment]
add productName in response

**Comment by miyaflowercat** [comment]
@james-tran-3005 discussed with @kuangxiang20240501 , since control users number are very limited in real case, we suggested using polling per 1 minute in FE to refresh the data.

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/4dd851c2-a541-4520-ba54-f70dafb891bb)
