### ISSUE TITLE
[Sonata] split Get Order by id into 4 use cases

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#73]
**current**

- current get order by id has 2 use cases : get UNI order by id, get Eline order by id

**expected**

- 4 use cases are required
   - - get UNI add order by id
        - - - use old use case
   - - get Eline add order by id
        - - - use old use case
   - - get UNI delete order by id
        - - - new
   - - get Eline delete order by id
       - - - new

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/7e686101-e62b-48d3-b52b-e56f1b790af4)
