### ISSUE TITLE
[Improvement][Inventory Read] UNI/Eline inventory list response body should remove the placeholder in target template

### ISSUE THREAD

**Issue by xuelianhan007** [mycloudnexus/kraken#83]
`  responseBody: |
        { 
          "id": "${segment}",
          "startDate": "@{{startDate}}",
          "status": "@{{status}}"
        }`
  The above placeholder @{{x}} should be  removed.
 The expected result:
 `  responseBody: |
        { 
          "id": "${segment}",
          "startDate": "",
          "status": ""
        }`

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/ff8c0b20-a8e9-4c38-a240-fff46322e65a)

**Comment by cheng0504** [comment]
curl --location 'https://kraken-hub-staging-cn.dev.consolecore.cc/mefApi/sonata/productInventory/v7/product?productOrderId=2acf853a-e4e5-471b-99d3-51cc598efd15&buyerId=qe1company' \

could get the response correctly after switching to json
![Image](https://github.com/user-attachments/assets/05912904-4a97-4026-bd78-8772237f9843)
