### ISSUE TITLE
[BUG] [control plane][FE] last deployment time always display even though no deployment yet

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#89]
**Describe the bug**
In use case mapping page, last deployment time tooltip of one use case always display even though no deployment in that env yet.
last deployment status is not correct either

**Expected behavior**
when last deployment of specific env is not available, hover the info icon should show nothing

**Screenshots**
<img width="1817" alt="Screen Shot 2024-11-08 at 11 50 55 AM" src="https://github.com/user-attachments/assets/c61b3efe-e04c-48dc-95d6-bc8efb76dc93">

**Additional context**
n/a

**Comment by cheng0504** [comment]
fixed
![Image](https://github.com/user-attachments/assets/0f3b0824-40de-4454-9056-ae8a5e64a813)
![Image](https://github.com/user-attachments/assets/0beee82c-5c29-4927-9ab4-52ef8c12a7fe)
