### ISSUE TITLE
[improvement] seller list page layout update

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#90]
**Issue desription**
1. No paddings between columns, when narrowing down to smaller page width, content from adjacent columns will stick together. 
2. Some field's label and value are vertical aligned, some are horizontal aligned
3. icon (blue bar) before each section title is not correctly aligned

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/9e3b93a5-218f-4278-b3e6-8412f2355c00">

**Expected behavior**
Enhance following the new layout design

![Image](https://github.com/user-attachments/assets/9493b89f-d306-4303-a2fe-63c0b5b12463)

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/d68357fa-bbbe-4d67-8c37-dfcac8e3c5d7)

**Comment by miyaflowercat** [comment]
![Image](https://github.com/user-attachments/assets/5b6550b4-e92f-4af5-aaff-e42074bfa295)

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/96d47813-5fe6-4af2-9572-9db227dd6fa3)

**Comment by cheng0504** [comment]
test server's content is not vertical alligned.

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/6121fdd8-35ea-422a-a2dc-fade6f9bba4e)
