### ISSUE TITLE
[FEATURE] build kraken version description file

### ISSUE THREAD

**Issue by kuangxiang20240501** [mycloudnexus/kraken#91]
### build kraken version description file

-  add enpoint to support build kraken verison description file
- collect product version/kraken version  when first installed

**Comment by cheng0504** [comment]
verified with pass.
![Image](https://github.com/user-attachments/assets/327f2f5d-e8b9-4255-9127-8cadd6331a6e)

**Comment by cheng0504** [comment]
request
`curl --location 'https://kraken-controller-cn.dev.consolecore.cc/products/mef.sonata/version-specification' \`

response
`---
kind: kraken.product.app.kraken
apiVersion: v1
metadata:
  name: Kraken App 1.0.0-snapshot
  key: kraken@1.0.0-snapshot
  labels:
    appVersion: 1.0.0-snapshot
    productVersion: V1.5.12
    productKey: mef.sonata
    productSpec: grace
    publishDate: 2024-11-14
  version: 1
spec:
  use-cases:
    - name: Product Ordering Management
      key: mef.sonata.api.order
      apiVersion: v10
      endpoints:
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: uni
            actionType: delete
        - path: "/mefApi/sonata/productOrderingManagement/v10/productOrder/{id}"
          method: get
          mapping-matrix:
            productType: uni
            actionType: add
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: access_e_line
            actionType: delete
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: access_e_line
            actionType: add
        - path: "/mefApi/sonata/productOrderingManagement/v10/productOrder/{id}"
          method: get
          mapping-matrix:
            productType: uni
            actionType: delete
        - path: "/mefApi/sonata/productOrderingManagement/v10/productOrder/{id}"
          method: get
          mapping-matrix:
            productType: access_e_line
            actionType: delete
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: uni
            actionType: add
        - path: "/mefApi/sonata/productOrderingManagement/v10/productOrder/{id}"
          method: get
          mapping-matrix:
            productType: access_e_line
            actionType: add
    - name: Product Inventory Management
      key: mef.sonata.api.inventory
      apiVersion: v7
      endpoints:
        - path: "/mefApi/sonata/productInventory/v7/product/{id}"
          method: get
          mapping-matrix:
            productType: uni
        - path: "/mefApi/sonata/productInventory/v7/product/{id}"
          method: get
          mapping-matrix:
            productType: access_e_line
        - path: /mefApi/sonata/productInventory/v7/product
          method: get
          mapping-matrix:
            productType: access_e_line
        - path: /mefApi/sonata/productInventory/v7/product
          method: get
          mapping-matrix:
            productType: uni
    - name: Geographic Address Management
      key: mef.sonata.api.serviceability.address
      apiVersion: v7
      endpoints:
        - path: /mefApi/sonata/geographicAddressManagement/v7/geographicAddressValidation
          method: post
          mapping-matrix:
            provideAlternative: false
            addressType: FieldedAddress
        - path: "/mefApi/sonata/geographicAddressManagement/v7/geographicAddress/{id}"
          method: get
          mapping-matrix:
            addressType: FieldedAddress
    - name: Quote Management
      key: mef.sonata.api.quote
      apiVersion: v8
      endpoints:
        - path: "/mefApi/sonata/quoteManagement/v8/quote/{id}"
          method: get
          mapping-matrix:
            productType: uni
            quoteLevel: firm
            syncMode: true
        - path: /mefApi/sonata/quoteManagement/v8/quote
          method: post
          mapping-matrix:
            productType: access_e_line
            actionType: add
            quoteLevel: firm
            syncMode: true
        - path: "/mefApi/sonata/quoteManagement/v8/quote/{id}"
          method: get
          mapping-matrix:
            productType: access_e_line
            quoteLevel: firm
            syncMode: true
        - path: /mefApi/sonata/quoteManagement/v8/quote
          method: post
          mapping-matrix:
            productType: uni
            actionType: add
            quoteLevel: firm
            syncMode: true
`

**Comment by cheng0504** [comment]
`---
kind: kraken.product.app.kraken
apiVersion: v1
metadata:
  name: Kraken App 1.0.0-snapshot
  key: kraken@1.0.0-snapshot
  labels:
    appVersion: 1.0.0-snapshot
    productVersion: V1.5.12
    productKey: mef.sonata
    productSpec: grace
    publishDate: 2024-11-14
  version: 1
spec:
  use-cases:
    - name: Product Ordering Management
      key: mef.sonata.api.order
      apiVersion: v10
      endpoints:
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: uni
            actionType: delete
        - path: "/mefApi/sonata/productOrderingManagement/v10/productOrder/{id}"
          method: get
          mapping-matrix:
            productType: uni
            actionType: add
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: access_e_line
            actionType: delete
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: access_e_line
            actionType: add
        - path: "/mefApi/sonata/productOrderingManagement/v10/productOrder/{id}"
          method: get
          mapping-matrix:
            productType: uni
            actionType: delete
        - path: "/mefApi/sonata/productOrderingManagement/v10/productOrder/{id}"
          method: get
          mapping-matrix:
            productType: access_e_line
            actionType: delete
        - path: /mefApi/sonata/productOrderingManagement/v10/productOrder
          method: post
          mapping-matrix:
            productType: uni
            actionType: add
        - path: "/mefApi/sonata/productOrderingManagement/v10/productOrder/{id}"
          method: get
          mapping-matrix:
            productType: access_e_line
            actionType: add
    - name: Product Inventory Management
      key: mef.sonata.api.inventory
      apiVersion: v7
      endpoints:
        - path: "/mefApi/sonata/productInventory/v7/product/{id}"
          method: get
          mapping-matrix:
            productType: uni
        - path: "/mefApi/sonata/productInventory/v7/product/{id}"
          method: get
          mapping-matrix:
            productType: access_e_line
        - path: /mefApi/sonata/productInventory/v7/product
          method: get
          mapping-matrix:
            productType: access_e_line
        - path: /mefApi/sonata/productInventory/v7/product
          method: get
          mapping-matrix:
            productType: uni
    - name: Geographic Address Management
      key: mef.sonata.api.serviceability.address
      apiVersion: v7
      endpoints:
        - path: /mefApi/sonata/geographicAddressManagement/v7/geographicAddressValidation
          method: post
          mapping-matrix:
            provideAlternative: false
            addressType: FieldedAddress
        - path: "/mefApi/sonata/geographicAddressManagement/v7/geographicAddress/{id}"
          method: get
          mapping-matrix:
            addressType: FieldedAddress
    - name: Quote Management
      key: mef.sonata.api.quote
      apiVersion: v8
      endpoints:
        - path: "/mefApi/sonata/quoteManagement/v8/quote/{id}"
          method: get
          mapping-matrix:
            productType: uni
            quoteLevel: firm
            syncMode: true
        - path: /mefApi/sonata/quoteManagement/v8/quote
          method: post
          mapping-matrix:
            productType: access_e_line
            actionType: add
            quoteLevel: firm
            syncMode: true
        - path: "/mefApi/sonata/quoteManagement/v8/quote/{id}"
          method: get
          mapping-matrix:
            productType: access_e_line
            quoteLevel: firm
            syncMode: true
        - path: /mefApi/sonata/quoteManagement/v8/quote
          method: post
          mapping-matrix:
            productType: uni
            actionType: add
            quoteLevel: firm
            syncMode: true
`
