### ISSUE TITLE
[BUG] Show empty state if no matched release when user filters by release status.

### ISSUE THREAD

**Issue by emmawu001** [mycloudnexus/kraken#93]
<img width="1628" alt="image" src="https://github.com/user-attachments/assets/bf005919-90a3-4a57-a107-a38f01a138d1">

**Expected behavior**
Show above empty state if no matched release when user filters by release status.

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/a077f702-b94a-4336-9c58-d3a5add8586c)
