### ISSUE TITLE
[BUG] [control plane][FE] HYBRID in targetLocation should be all upper cases when saving the use case mapping

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#95]
**Describe the bug**
<img width="2550" alt="Screen Shot 2024-11-08 at 3 57 02 PM" src="https://github.com/user-attachments/assets/6fe576ce-3f89-46d9-bdb5-60794ea8650e">

**Expected behavior**
HYBRID in targetLocation should be all upper cases

**Comment by cheng0504** [comment]
pass
![Image](https://github.com/user-attachments/assets/96ad3b64-34fb-4106-ac56-d18ab3abbd75)
