### ISSUE TITLE
[BUG] [data plane] list parsing is not correctly

### ISSUE THREAD

**Issue by miyaflowercat** [mycloudnexus/kraken#98]
**Describe the bug**
value of sonata response property in list type is in strange format
` "tags": [
        "\"\\\"offnet\\\"\"",
        "\"\\\"free\\\"\""
      ],`

value from target side
`    "tags": [
      "offnet",
      "free"
    ],`

**Expected behavior**
list parsing should be working normally

**Comment by cheng0504** [comment]
![Image](https://github.com/user-attachments/assets/0c37e2c9-5fe4-4fdd-828f-464ff54a68fb)
pass
